/*
 * This file was automatically generated by EvoSuite
 * Mon May 04 17:32:42 GMT 2026
 */

package org.Model.Playlist;
import java.util.Arrays;

import org.junit.Test;
import org.junit.Ignore;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.Model.Music.Music;
@Ignore("EvoSuite: relies on static id reset")
public class Playlist_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      // Undeclared exception!
      try { 
        playlist0.getMusicBYIndex(285);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // \u00CDndice fora dos limites da lista de m\u00FAsicas.
         //
         verifyException("org.Model.Playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Playlist playlist0 = new Playlist("\u0000w`NjcR1yl;'4mp", "", (List<Music>) null);
      Music music0 = new Music();
      playlist0.addMusic(music0);
      playlist0.removeMusic(music0);
      assertEquals("", playlist0.getAutor());
      assertEquals("\u0000w`NjcR1yl;'4mp", playlist0.getName());
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      List<Music> list0 = playlist0.getMusics();
      Playlist playlist1 = new Playlist((String) null, (String) null, list0);
      playlist1.getName();
      assertEquals(1, playlist1.getId());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Music music0 = new Music();
      List<Music> list0 = Arrays.asList(music0, music0, music0, music0, music0, music0, music0, music0, music0, music0);
      Playlist playlist0 = new Playlist("iVR 3Y", "iVR 3Y", list0);
      playlist0.getName();
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      playlist0.addMusic((Music) null);
      playlist0.getMusicBYIndex(0);
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      Music music0 = new Music("mHqeEM:]", "M,(K[p%sG&*", "V", "pMb3YN\u0006&X&", "mHqeEM:]", "r@qh/K1cEMN", "M,(K[p%sG&*", 1379, true);
      music0.play();
      playlist0.addMusic(music0);
      playlist0.getMusicBYIndex(0);
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      Music music0 = new Music("mHqeEM:]", "M,(K[p%sG&*", "V", "pMb3YN\u0006&X&", "mHqeEM:]", "r@qh/K1cEMN", "M,(K[p%sG&*", 1379, true);
      music0.setReproductions((-799));
      playlist0.addMusic(music0);
      playlist0.getMusicBYIndex(0);
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Playlist playlist0 = new Playlist("\u0000w`NjcR1yl;'4mp", "", (List<Music>) null);
      Music music0 = new Music();
      playlist0.addMusic(music0);
      playlist0.getMusicBYIndex(0);
      assertEquals("", playlist0.getAutor());
      assertEquals("\u0000w`NjcR1yl;'4mp", playlist0.getName());
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Playlist playlist0 = new Playlist("NYi;Qk..", "NYi;Qk..");
      Music music0 = new Music("tu\"M2oLFK!::0q+;o", "r@qh/K1cEMJaN", "NYi;Qk..", "XBUh(.Xo", "NYi;Qk..", "Interprete: ", "NYi;Qk..", (-3312), true);
      playlist0.addMusic(music0);
      playlist0.getMusicBYIndex(0);
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Playlist playlist0 = new Playlist("\u0000w`NjcR1yl;'4mp", "", (List<Music>) null);
      assertEquals("", playlist0.getAutor());
      assertEquals("\u0000w`NjcR1yl;'4mp", playlist0.getName());
      
      Playlist playlist1 = new Playlist("\u0000w`NjcR1yl;'4mp", "Playlist{nome='', autor='', musicas=[Nome: \u0000w`NjcR1yl;'4mp\nInterprete: \nEditora: \nLetra: \nLinhas Musicais: \nGenero Musical: \nAlbum: \nDuracao: 0\nReproducoes: 0\nExplicita: Nao\n]}");
      int int0 = playlist1.getId();
      assertEquals(1, int0);
      assertEquals("Playlist{nome='', autor='', musicas=[Nome: \u0000w`NjcR1yl;'4mp\nInterprete: \nEditora: \nLetra: \nLinhas Musicais: \nGenero Musical: \nAlbum: \nDuracao: 0\nReproducoes: 0\nExplicita: Nao\n]}", playlist1.getAutor());
      assertEquals("\u0000w`NjcR1yl;'4mp", playlist1.getName());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      playlist0.setId((-625));
      int int0 = playlist0.getId();
      assertEquals((-625), int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Playlist playlist0 = new Playlist("Playlist{nome='', autor='', musicas=[]}", (String) null, (List<Music>) null);
      String string0 = playlist0.getAutor();
      assertNull(string0);
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      playlist0.setAutor("xkwQ:tb");
      playlist0.getAutor();
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Playlist playlist1 = new Playlist("@xpw*%t{~", "");
      Playlist playlist2 = playlist1.clone();
      assertEquals(1, playlist2.getId());
      assertEquals("@xpw*%t{~", playlist2.getName());
      assertEquals("", playlist2.getAutor());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      playlist0.setId((-172));
      playlist0.clone();
      assertEquals((-172), playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      // Undeclared exception!
      try { 
        playlist0.setMusics((List<Music>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      playlist0.addMusic((Music) null);
      // Undeclared exception!
      try { 
        playlist0.getMusics();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Playlist playlist0 = new Playlist((String) null, (String) null);
      Playlist playlist1 = playlist0.clone();
      // Undeclared exception!
      try { 
        playlist0.equals(playlist1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      playlist0.addMusic((Music) null);
      // Undeclared exception!
      try { 
        playlist0.addMusic((Music) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      try {
                new Playlist((Playlist) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Playlist playlist0 = new Playlist("\u0000w`NjcR1yl;'4mp", "", (List<Music>) null);
      int int0 = playlist0.getId();
      assertEquals("", playlist0.getAutor());
      assertEquals(0, int0);
      assertEquals("\u0000w`NjcR1yl;'4mp", playlist0.getName());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      // Undeclared exception!
      try { 
        playlist0.getMusicBYIndex(0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // \u00CDndice fora dos limites da lista de m\u00FAsicas.
         //
         verifyException("org.Model.Playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      // Undeclared exception!
      try { 
        playlist0.getMusicBYIndex((-2871));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // \u00CDndice fora dos limites da lista de m\u00FAsicas.
         //
         verifyException("org.Model.Playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Music music0 = new Music();
      List<Music> list0 = Arrays.asList(music0);
      Playlist playlist0 = new Playlist("YssIreBq;1t8]4t6E", "\n", list0);
      try { 
        playlist0.addMusic(music0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // J\u00E1 existe: 
         //
         verifyException("org.Model.Playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      Playlist playlist1 = new Playlist();
      assertTrue(playlist1.equals((Object)playlist0));
      
      playlist1.setAutor("V");
      boolean boolean0 = playlist1.equals(playlist0);
      assertFalse(playlist1.equals((Object)playlist0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      Playlist playlist1 = new Playlist();
      boolean boolean0 = playlist1.equals(playlist0);
      assertEquals(1, playlist1.getId());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      Playlist playlist1 = new Playlist("@xpw*%t{~", "");
      boolean boolean0 = playlist1.equals(playlist0);
      assertEquals(1, playlist1.getId());
      assertFalse(boolean0);
      assertEquals("", playlist1.getAutor());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      boolean boolean0 = playlist0.equals(playlist0);
      assertEquals(0, playlist0.getId());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      boolean boolean0 = playlist0.equals("Playlist{nome='@xpw*%t{~', autor='', musicas=[]}");
      assertFalse(boolean0);
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Playlist playlist0 = new Playlist("\u0000w`NjcR1yl;'4mp", "", (List<Music>) null);
      Music music0 = new Music();
      playlist0.addMusic(music0);
      List<Music> list0 = playlist0.getMusics();
      playlist0.setMusics(list0);
      assertEquals("", playlist0.getAutor());
      assertEquals(0, playlist0.getId());
      assertTrue(list0.contains(music0));
      assertEquals("\u0000w`NjcR1yl;'4mp", playlist0.getName());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      playlist0.getName();
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      playlist0.setName("7v?mr8:jWv^-gpa!2?");
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      Music music0 = new Music();
      playlist0.removeMusic(music0);
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Playlist playlist0 = new Playlist("\u0000w`NjcR1yl;'4mp", "", (List<Music>) null);
      playlist0.hashCode();
      assertEquals("", playlist0.getAutor());
      assertEquals(0, playlist0.getId());
      assertEquals("\u0000w`NjcR1yl;'4mp", playlist0.getName());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      playlist0.getAutor();
      assertEquals(0, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      Playlist playlist1 = new Playlist(playlist0);
      assertEquals(0, playlist1.getId());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      String string0 = playlist0.toString();
      assertEquals("Playlist{nome='', autor='', musicas=[]}", string0);
      assertEquals(0, playlist0.getId());
  }
}
