/*
 * This file was automatically generated by EvoSuite
 * Mon May 04 17:32:16 GMT 2026
 */

package org.Model.Album;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import org.Model.Album.Album;
import org.Model.Music.Music;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Album_ESTest extends Album_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("&P:&i97pRKT_u5Q[9", "&P:&i97pRKT_u5Q[9", linkedList0);
      Album album1 = new Album(album0);
      assertEquals("&P:&i97pRKT_u5Q[9", album1.getName());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Album album0 = new Album("\n", "\n");
      album0.removeMusic((Music) null);
      assertEquals("\n", album0.getName());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Album album0 = new Album("9n|sPS8$9;;K9@}!d", "9n|sPS8$9;;K9@}!d");
      album0.addMusic((Music) null);
      assertEquals("9n|sPS8$9;;K9@}!d", album0.getArtist());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Music music0 = new Music(">", ">", "", "", "Nome: ", "", "7zRa", 1745, true);
      List<Music> list0 = List.of(music0, music0, music0, music0, music0, music0, music0, music0);
      Album album0 = new Album(">", ">", list0);
      album0.setName((String) null);
      String string0 = album0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Album album0 = new Album();
      String string0 = album0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Album album0 = new Album("Yk1@", "Yk1@");
      List<Music> list0 = album0.getMusics();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Album album0 = new Album();
      Music music0 = new Music("\n", "\n", "Interprete: ", "Interprete: ", (String) null, "Interprete: ", "ICYA%r{>6YX(\"*ix)t", (-1), false);
      music0.play();
      List<Music> list0 = List.of(music0, music0, music0, music0);
      album0.setMusics(list0);
      Music music1 = album0.getMusicByName("\n");
      assertEquals((-1), music1.getDuration());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Album album0 = new Album();
      Music music0 = new Music("", "", "Interprete: ", "Interprete: ", (String) null, (String) null, "ICYA r{>6YX*ix)4", (-1), true);
      music0.setReproductions((-1));
      List<Music> list0 = List.of(music0, music0, music0, music0);
      album0.setMusics(list0);
      Music music1 = album0.getMusicByName("");
      assertEquals((-1), music1.getDuration());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Music music0 = new Music();
      List<Music> list0 = List.of(music0, music0, music0);
      Album album0 = new Album("", "", list0);
      Music music1 = album0.getMusicByName("");
      assertEquals("", music1.getName());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Music music0 = new Music(">", ">", "", "", "Nome: ", "", "7zRa", 1745, true);
      List<Music> list0 = List.of(music0, music0, music0, music0, music0, music0, music0, music0);
      Album album0 = new Album(">", ">", list0);
      Music music1 = album0.getMusicByName(">");
      assertEquals("", music1.getPublisher());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Album album0 = new Album();
      album0.setArtist((String) null);
      String string0 = album0.getArtist();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("Artista: ", "o<0R~4${|6mB~3^3", linkedList0);
      String string0 = album0.getArtist();
      assertEquals("Artista: ", album0.getName());
      assertEquals("o<0R~4${|6mB~3^3", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("}", "", linkedList0);
      Album album1 = album0.clone();
      assertEquals("}", album1.getName());
      assertEquals("", album1.getArtist());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Album album0 = new Album();
      Music music0 = new Music();
      List<Music> list0 = List.of(music0, music0, music0, music0);
      album0.setMusics(list0);
      // Undeclared exception!
      try { 
        album0.removeMusic(music0);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.ImmutableCollections", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.getMusics();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.getMusicByName("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Music music0 = new Music();
      List<Music> list0 = List.of(music0, music0, music0, music0);
      Album album0 = new Album("org.Model.Album.Album", "org.Model.Album.Album", list0);
      album0.setMusics(list0);
      // Undeclared exception!
      try { 
        album0.addMusic(music0);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.ImmutableCollections", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Album album0 = null;
      try {
        album0 = new Album((String) null, (String) null, (List<Music>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Music music0 = new Music(">", ">", "", "", "Nome: ", "", "7zRa", 1745, true);
      List<Music> list0 = List.of(music0, music0, music0, music0, music0, music0, music0, music0);
      Album album0 = new Album(">", ">", list0);
      String string0 = album0.getName();
      assertEquals(">", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Album album0 = new Album();
      String string0 = album0.getArtist();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Music music0 = new Music("", "Artista: ", "", "", "\n", "", "", (-2900), true);
      List<Music> list0 = List.of(music0, music0);
      Album album0 = new Album("\n", "?*h8m7CD", list0);
      Music music1 = album0.getMusicByName("v");
      assertEquals("?*h8m7CD", album0.getArtist());
      assertNull(music1);
      assertEquals("\n", album0.getName());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Music music0 = new Music("", "Artista: ", "", "", "\n", "", "", (-2900), true);
      List<Music> list0 = List.of(music0, music0);
      Album album0 = new Album("\n", "?*h8m7CD", list0);
      String string0 = album0.toString();
      assertEquals("Album: \n\nArtista: ?*h8m7CD\nM\u00FAsicas:\nNome: \nInterprete: Artista: \nEditora: \nLetra: \nLinhas Musicais: \n\nGenero Musical: \nAlbum: \nDuracao: -2900\nReproducoes: 0\nExplicita: Sim\n\nNome: \nInterprete: Artista: \nEditora: \nLetra: \nLinhas Musicais: \n\nGenero Musical: \nAlbum: \nDuracao: -2900\nReproducoes: 0\nExplicita: Sim\n\n", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Music music0 = new Music("", "Artista: ", "", "", "\n", "", "", (-2900), true);
      List<Music> list0 = List.of(music0, music0);
      Album album0 = new Album("\n", "?*h8m7CD", list0);
      List<Music> list1 = album0.getMusics();
      assertEquals("?*h8m7CD", album0.getArtist());
      assertTrue(list1.contains(music0));
      assertEquals("\n", album0.getName());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.addMusic((Music) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Album album0 = new Album("&P:&i97pRKT_u5Q[9", "?*h8m7CD");
      assertEquals("?*h8m7CD", album0.getArtist());
      assertEquals("&P:&i97pRKT_u5Q[9", album0.getName());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.clone();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.removeMusic((Music) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Album album0 = new Album();
      Album album1 = null;
      try {
        album1 = new Album(album0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Album.Album", e);
      }
  }
}
