/*
 * This file was automatically generated by EvoSuite
 * Sat May 02 22:22:23 GMT 2026
 */

package org.Model.Album;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;
import org.Model.Album.Album;
import org.Model.Music.Music;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Album_ESTest extends Album_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Album album0 = new Album("v]=&}", "");
      assertEquals("v]=&}", album0.getName());
      assertEquals("", album0.getArtist());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("", "HtJc{ = h15n", linkedList0);
      Album album1 = new Album(album0);
      assertEquals("HtJc{ = h15n", album1.getArtist());
      assertEquals("", album1.getName());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Music music0 = new Music();
      List<Music> list0 = List.of(music0, music0, music0, music0, music0, music0);
      Album album0 = new Album((String) null, (String) null, list0);
      String string0 = album0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Music music0 = new Music();
      List<Music> list0 = List.of(music0, music0, music0, music0, music0, music0);
      Album album0 = new Album((String) null, (String) null, list0);
      album0.setName("EJx7.7\"Z.es})X");
      String string0 = album0.getName();
      assertEquals("EJx7.7\"Z.es})X", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Album album0 = new Album("", "");
      List<Music> list0 = album0.getMusics();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("Nome: ", "iX&_^y*G_/<m%A", linkedList0);
      String string0 = ".iK\\uy{fmTnC|RSsW";
      Music music0 = new Music("iX&_^y*G_/<m%A", "Nome: ", "lXD#QNH)9k*W{R", string0, "Album: ", "lXD#QNH)9k*W{R", string0, (-1968526675), true);
      album0.addMusic(music0);
      Music music1 = album0.getMusicByName("iX&_^y*G_/<m%A");
      assertEquals("Nome: ", album0.getName());
      assertNotNull(music1);
      assertEquals("iX&_^y*G_/<m%A", album0.getArtist());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Album album0 = new Album("", "");
      Music music0 = new Music();
      music0.setReproductions(2423);
      album0.addMusic(music0);
      Music music1 = album0.getMusicByName("");
      assertEquals(0, music1.getDuration());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Album album0 = new Album("'jU56gnd*_cW<5j", "'jU56gnd*_cW<5j");
      Music music0 = new Music("qB_I+:_YC", (String) null, "qB_I+:_YC", "'jU56gnd*_cW<5j", ",", "tx&", ",", (-1953944956), false);
      music0.setReproductions((-2800));
      album0.addMusic(music0);
      Music music1 = album0.getMusicByName("qB_I+:_YC");
      assertEquals(",", music1.getMusicalFigures());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Music music0 = new Music();
      List<Music> list0 = List.of(music0, music0, music0, music0, music0, music0, music0);
      music0.setName("EKUsdRd/+");
      music0.setDuration(971);
      Album album0 = new Album("Editora: ", "EKUsdRd/+", list0);
      Music music1 = album0.getMusicByName("EKUsdRd/+");
      assertEquals("Editora: ", album0.getName());
      assertNotNull(music1);
      assertEquals("EKUsdRd/+", album0.getArtist());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Music music0 = new Music();
      List<Music> list0 = List.of(music0, music0, music0, music0, music0, music0);
      Album album0 = new Album((String) null, (String) null, list0);
      String string0 = album0.getArtist();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Music music0 = new Music();
      List<Music> list0 = List.of(music0, music0, music0, music0, music0, music0);
      Album album0 = new Album((String) null, (String) null, list0);
      album0.setArtist("sH*z;IfU(@u#| z/");
      String string0 = album0.getArtist();
      assertEquals("sH*z;IfU(@u#| z/", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Album album0 = new Album();
      Music music0 = new Music();
      // Undeclared exception!
      try { 
        album0.removeMusic(music0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.getMusics();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.getMusicByName((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.clone();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Music music0 = new Music();
      List<Music> list0 = List.of(music0, music0, music0, music0, music0, music0, music0);
      Album album0 = new Album("DKUsdRd/+", "DKUsdRd/+", list0);
      album0.setMusics(list0);
      // Undeclared exception!
      try { 
        album0.addMusic(music0);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.ImmutableCollections", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.addMusic((Music) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      List<Music> list0 = linkedList0.subList(0, 0);
      Music music0 = new Music();
      linkedList0.add(music0);
      Album album0 = null;
      try {
        album0 = new Album("9T~\"UD$", "9T~\"UD$", list0);
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.AbstractList$SubList", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Album album0 = null;
      try {
        album0 = new Album("Album: ", "Album: ", (List<Music>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Album album0 = new Album("", "");
      String string0 = album0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Album album0 = new Album("", "");
      String string0 = album0.getArtist();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Album album0 = new Album();
      Album album1 = null;
      try {
        album1 = new Album(album0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Music music0 = new Music();
      List<Music> list0 = List.of(music0, music0, music0, music0, music0, music0, music0);
      Album album0 = new Album("qB_I+:_YC", "[?CaOtthx,}V(", list0);
      Music music1 = album0.getMusicByName("Artista: ");
      assertNull(music1);
      assertEquals("qB_I+:_YC", album0.getName());
      assertEquals("[?CaOtthx,}V(", album0.getArtist());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Music music0 = new Music();
      List<Music> list0 = List.of(music0, music0, music0, music0, music0, music0, music0);
      Album album0 = new Album("qB_I+:_YC", "[?CaOtthx,}V(", list0);
      String string0 = album0.toString();
      assertEquals("Album: qB_I+:_YC\nArtista: [?CaOtthx,}V(\nM\u00FAsicas:\nNome: \nInterprete: \nEditora: \nLetra: \nLinhas Musicais: \nGenero Musical: \nAlbum: \nDuracao: 0\nReproducoes: 0\nExplicita: Nao\n\nNome: \nInterprete: \nEditora: \nLetra: \nLinhas Musicais: \nGenero Musical: \nAlbum: \nDuracao: 0\nReproducoes: 0\nExplicita: Nao\n\nNome: \nInterprete: \nEditora: \nLetra: \nLinhas Musicais: \nGenero Musical: \nAlbum: \nDuracao: 0\nReproducoes: 0\nExplicita: Nao\n\nNome: \nInterprete: \nEditora: \nLetra: \nLinhas Musicais: \nGenero Musical: \nAlbum: \nDuracao: 0\nReproducoes: 0\nExplicita: Nao\n\nNome: \nInterprete: \nEditora: \nLetra: \nLinhas Musicais: \nGenero Musical: \nAlbum: \nDuracao: 0\nReproducoes: 0\nExplicita: Nao\n\nNome: \nInterprete: \nEditora: \nLetra: \nLinhas Musicais: \nGenero Musical: \nAlbum: \nDuracao: 0\nReproducoes: 0\nExplicita: Nao\n\nNome: \nInterprete: \nEditora: \nLetra: \nLinhas Musicais: \nGenero Musical: \nAlbum: \nDuracao: 0\nReproducoes: 0\nExplicita: Nao\n\n", string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Music music0 = new Music();
      List<Music> list0 = List.of(music0, music0, music0, music0, music0, music0, music0);
      Album album0 = new Album("qB_I+:_YC", "[?CaOtthx,}V(", list0);
      album0.getMusics();
      assertEquals("[?CaOtthx,}V(", album0.getArtist());
      assertEquals("qB_I+:_YC", album0.getName());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      LinkedList<Music> linkedList0 = new LinkedList<Music>();
      Album album0 = new Album("||+;.W?r|T", (String) null, linkedList0);
      album0.removeMusic((Music) null);
      assertNull(album0.getArtist());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Album album0 = new Album();
      Music music0 = new Music();
      List<Music> list0 = List.of(music0, music0, music0);
      album0.setMusics(list0);
      // Undeclared exception!
      try { 
        album0.removeMusic(music0);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.ImmutableCollections", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Album album0 = new Album("'jU56gnd*_cW<5j", "'jU56gnd*_cW<5j");
      Album album1 = album0.clone();
      assertFalse(album1.equals((Object)album0));
  }
}
