/*
 * This file was automatically generated by EvoSuite
 * Mon May 04 17:33:29 GMT 2026
 */

package org.Model.User;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.util.LinkedList;
import java.util.List;
import org.Model.Music.Music;
import org.Model.Music.MusicReproduction;
import org.Model.Plan.Plan;
import org.Model.Plan.PlanFree;
import org.Model.Plan.PlanPremiumBase;
import org.Model.Plan.PlanPremiumTop;
import org.Model.Playlist.Playlist;
import org.Model.User.User;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class User_ESTest extends User_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      List<Playlist> list0 = List.of(playlist0, playlist0, playlist0);
      Music music0 = new Music();
      LocalDate localDate0 = MockLocalDate.ofEpochDay((-36L));
      MusicReproduction musicReproduction0 = new MusicReproduction(music0, localDate0);
      List<MusicReproduction> list1 = List.of(musicReproduction0, musicReproduction0, musicReproduction0);
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      User user0 = new User("\u2022", "`KLs<0~V2?V,B", "Q&", "8ybJeOhd", planPremiumBase0, list0, list1);
      LocalDate localDate1 = MockLocalDate.ofYearDay((-1059), 3);
      int int0 = user0.getMusicReproductionsCount(localDate1, localDate0);
      assertEquals("`KLs<0~V2?V,B", user0.getEmail());
      assertEquals(0, int0);
      assertEquals("\u2022", user0.getUsername());
      assertEquals("8ybJeOhd", user0.getPassword());
      assertEquals("Q&", user0.getAdress());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      User user0 = new User();
      ZoneOffset zoneOffset0 = ZoneOffset.ofTotalSeconds((-1504));
      LocalDate localDate0 = MockLocalDate.now((ZoneId) zoneOffset0);
      LocalDate localDate1 = MockLocalDate.ofEpochDay((-1504));
      int int0 = user0.getMusicReproductionsCount(localDate0, localDate1);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      User user0 = new User();
      Playlist playlist0 = new Playlist();
      user0.addPlaylistToLibrary(playlist0);
      try { 
        user0.removeMusicFromPlaylist((Music) null, 1);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: 1
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      PlanFree planFree0 = new PlanFree(planPremiumBase0);
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop(planFree0);
      Playlist playlist0 = new Playlist((String) null, "[rAmC");
      List<Playlist> list0 = List.of(playlist0);
      LinkedList<MusicReproduction> linkedList0 = new LinkedList<MusicReproduction>();
      User user0 = new User("%qNr\u0004B&", "Utilizadores Free n\u00E3o possuem playlists.", "[rAmC", (String) null, planPremiumTop0, list0, linkedList0);
      try { 
        user0.getPlaylistById((-10));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: -10
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      List<Music> list0 = playlist0.getMusics();
      Playlist playlist1 = new Playlist("TU.Mc!{{ ;[Q`", "`KLs<0~V2?V,B", list0);
      List<Playlist> list1 = List.of(playlist1, playlist1, playlist0);
      Music music0 = new Music();
      LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
      MusicReproduction musicReproduction0 = new MusicReproduction(music0, localDate0);
      List<MusicReproduction> list2 = List.of(musicReproduction0, musicReproduction0, musicReproduction0);
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      PlanFree planFree0 = new PlanFree(planPremiumBase0);
      User user0 = new User("TU.Mc!{{ ;[Q`", "org.Model.User.User", "Utilizadores Free n\u00E3o podem adicionar m\u00FAsicas a playlists.", "dr", planFree0, list1, list2);
      try { 
        user0.addMusicPlaylist(0, music0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o tem permiss\u00E3o para aceder a este recurso: S\u00F3 o autor da playlist pode adicionar m\u00FAsicas.
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop();
      PlanFree planFree0 = new PlanFree(planPremiumTop0);
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase(planFree0);
      User user0 = new User();
      List<Playlist> list0 = user0.getPlaylists();
      LinkedList<MusicReproduction> linkedList0 = new LinkedList<MusicReproduction>();
      User user1 = new User("", "", "", "", planPremiumBase0, list0, linkedList0);
      boolean boolean0 = user1.hasLibrary();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop();
      User user0 = new User();
      List<Playlist> list0 = user0.getPlaylists();
      List<MusicReproduction> list1 = user0.getMusicReproductions();
      User user1 = new User((String) null, (String) null, "", (String) null, planPremiumTop0, list0, list1);
      String string0 = user1.getUsername();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      User user0 = new User();
      String string0 = user0.getUsername();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      Playlist playlist1 = new Playlist(playlist0);
      List<Music> list0 = playlist0.getMusics();
      Playlist playlist2 = new Playlist("TU.Mc!{{ ;[Q`", "`KLs<0~V2?V,B", list0);
      List<Playlist> list1 = List.of(playlist2, playlist2, playlist1);
      Music music0 = new Music();
      LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
      MusicReproduction musicReproduction0 = new MusicReproduction(music0, localDate0);
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop();
      List<MusicReproduction> list2 = List.of(musicReproduction0);
      User user0 = new User("\u2022", "HE4^sq>t", "a^P'-0`!Y%Obz|9BO", "S\u00F3 o autor da playlist pode adicionar m\u00FAsicas.", planPremiumTop0, list1, list2);
      user0.getPlaylistById(2);
      assertEquals("HE4^sq>t", user0.getEmail());
      assertEquals("S\u00F3 o autor da playlist pode adicionar m\u00FAsicas.", user0.getPassword());
      assertEquals("a^P'-0`!Y%Obz|9BO", user0.getAdress());
      assertEquals("\u2022", user0.getUsername());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      List<Playlist> list0 = List.of(playlist0, playlist0, playlist0);
      User user0 = new User("|Mo)#Elr:sq", "rA:", "p\u2022", "\uD83C\uDFB5 [#%03d] %-25s | Autor: %-15s\n");
      List<MusicReproduction> list1 = user0.getMusicReproductions();
      User user1 = new User("oGcYrcTQA)tg}#Yt[", "S\u00F3 o autor da playlist pode remover m\u00FAsicas.", "p\u2022", "`KLs<0~V2?V,B", (Plan) null, list0, list1);
      user1.getPlan();
      assertEquals("p\u2022", user0.getAdress());
      assertEquals("oGcYrcTQA)tg}#Yt[", user1.getUsername());
      assertEquals("rA:", user0.getEmail());
      assertEquals("p\u2022", user1.getAdress());
      assertEquals("|Mo)#Elr:sq", user0.getUsername());
      assertEquals("S\u00F3 o autor da playlist pode remover m\u00FAsicas.", user1.getEmail());
      assertEquals("\uD83C\uDFB5 [#%03d] %-25s | Autor: %-15s\n", user0.getPassword());
      assertEquals("`KLs<0~V2?V,B", user1.getPassword());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop();
      PlanPremiumTop planPremiumTop1 = new PlanPremiumTop(planPremiumTop0);
      User user0 = new User((String) null, "org.Model.User.User", "", "~");
      List<Playlist> list0 = user0.getPlaylists();
      List<MusicReproduction> list1 = user0.getMusicReproductions();
      User user1 = new User("org.Model.User.User", "org.Model.User.User", "org.Model.User.User", "org.Model.User.User", planPremiumTop1, list0, list1);
      user1.getPlan();
      assertEquals("~", user0.getPassword());
      assertEquals("org.Model.User.User", user0.getEmail());
      assertEquals("", user0.getAdress());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop(planPremiumBase0);
      PlanFree planFree0 = new PlanFree(planPremiumTop0);
      User user0 = new User();
      List<Playlist> list0 = user0.getPlaylists();
      planFree0.setPoints((-3406));
      List<MusicReproduction> list1 = user0.getMusicReproductions();
      User user1 = new User("Utilizadores Free n\u00E3o podem adicionar m\u00FAsicas a playlists.", "\u2022", "wghV$#v", "Utilizadores Free n\u00E3o podem adicionar m\u00FAsicas a playlists.", planFree0, list0, list1);
      user1.getPlan();
      assertEquals("wghV$#v", user1.getAdress());
      assertEquals("\u2022", user1.getEmail());
      assertEquals("Utilizadores Free n\u00E3o podem adicionar m\u00FAsicas a playlists.", user1.getPassword());
      assertEquals("Utilizadores Free n\u00E3o podem adicionar m\u00FAsicas a playlists.", user1.getUsername());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      User user0 = new User("EmdSr*^g(-PpHW5Y", "EmdSr*^g(-PpHW5Y", "EmdSr*^g(-PpHW5Y", "EmdSr*^g(-PpHW5Y");
      String string0 = user0.getPassword();
      assertEquals("EmdSr*^g(-PpHW5Y", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      User user0 = new User("EmdSr*^g(-PpHW5Y", "EmdSr*^g(-PpHW5Y", "V/tB!+,O!X", "");
      String string0 = user0.getPassword();
      assertEquals("", string0);
      assertEquals("EmdSr*^g(-PpHW5Y", user0.getEmail());
      assertEquals("V/tB!+,O!X", user0.getAdress());
      assertEquals("EmdSr*^g(-PpHW5Y", user0.getUsername());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      List<Playlist> list0 = List.of(playlist0, playlist0, playlist0);
      Music music0 = new Music();
      LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
      MusicReproduction musicReproduction0 = new MusicReproduction(music0, localDate0);
      List<MusicReproduction> list1 = List.of(musicReproduction0, musicReproduction0, musicReproduction0);
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      PlanFree planFree0 = new PlanFree(planPremiumBase0);
      User user0 = new User("TU.Mc!{{ ;[Q`", "org.Model.User.User", "Utilizadores Free n\u00E3o podem adicionar m\u00FAsicas a playlists.", "dr", planFree0, list0, list1);
      user0.getMusicReproductions();
      assertEquals("TU.Mc!{{ ;[Q`", user0.getUsername());
      assertEquals("org.Model.User.User", user0.getEmail());
      assertEquals("dr", user0.getPassword());
      assertEquals("Utilizadores Free n\u00E3o podem adicionar m\u00FAsicas a playlists.", user0.getAdress());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop();
      User user0 = new User();
      List<Playlist> list0 = user0.getPlaylists();
      List<MusicReproduction> list1 = user0.getMusicReproductions();
      User user1 = new User((String) null, (String) null, "", (String) null, planPremiumTop0, list0, list1);
      String string0 = user1.getEmail();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      User user0 = new User("", "", "", "l4Zj");
      String string0 = user0.getEmail();
      assertEquals("", user0.getAdress());
      assertEquals("", user0.getUsername());
      assertEquals("l4Zj", user0.getPassword());
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      User user0 = new User();
      user0.setAdress((String) null);
      String string0 = user0.getAdress();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      User user0 = new User();
      user0.setAdress("Q&");
      String string0 = user0.getAdress();
      assertEquals("Q&", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      User user0 = new User("U", "U", "U", (String) null);
      // Undeclared exception!
      try { 
        user0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      User user0 = new User();
      // Undeclared exception!
      try { 
        user0.setPlaylists((List<Playlist>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      User user0 = new User();
      // Undeclared exception!
      try { 
        user0.setMusicReproductions((List<MusicReproduction>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      User user0 = new User();
      user0.addPlaylistToLibrary((Playlist) null);
      // Undeclared exception!
      try { 
        user0.removeMusicFromPlaylist((Music) null, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      User user0 = new User("A", "A", "A", "A");
      user0.setPlan((Plan) null);
      // Undeclared exception!
      try { 
        user0.namePlaylists();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      User user0 = new User("A", "A", "A", "A");
      user0.setPlan((Plan) null);
      // Undeclared exception!
      try { 
        user0.hasLibrary();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      User user0 = new User();
      user0.addPlaylistToLibrary((Playlist) null);
      // Undeclared exception!
      try { 
        user0.getUserPlaylistCount();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      User user0 = new User();
      user0.addPlaylistToLibrary((Playlist) null);
      // Undeclared exception!
      try { 
        user0.getPlaylists();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      User user0 = new User();
      user0.setPlan((Plan) null);
      // Undeclared exception!
      try { 
        user0.getPlaylistById(1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      User user0 = new User("T", "T", "T", "T");
      User user1 = new User();
      user0.setUsername((String) null);
      // Undeclared exception!
      try { 
        user0.equals(user1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      User user0 = new User();
      user0.addPlaylistToLibrary((Playlist) null);
      // Undeclared exception!
      try { 
        user0.clone();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      User user0 = new User();
      user0.addPlaylistToLibrary((Playlist) null);
      // Undeclared exception!
      try { 
        user0.changePlaylistAutor("$e.R=yI|/8SQ]");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      User user0 = new User();
      user0.setPlan((Plan) null);
      // Undeclared exception!
      try { 
        user0.addPoints();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      User user0 = new User();
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      PlanFree planFree0 = new PlanFree(planPremiumBase0);
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop(planFree0);
      Playlist playlist0 = new Playlist((String) null, "[rAmC");
      List<Playlist> list0 = List.of(playlist0);
      List<MusicReproduction> list1 = user0.getMusicReproductions();
      User user1 = new User((String) null, "pR\"Btx_K", "UtilizIdores Free n\u00E3g hossuem playlists", "`Y", planPremiumTop0, list0, list1);
      Playlist playlist1 = user1.getPlaylistById(0);
      try { 
        user1.addPlaylistToLibrary(playlist1);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // J\u00E1 existe: null
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      User user0 = new User("I", "I", "I", "I");
      user0.setPlan((Plan) null);
      // Undeclared exception!
      try { 
        user0.addPlaylist("J");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      User user0 = new User();
      user0.addPlaylistToLibrary((Playlist) null);
      // Undeclared exception!
      try { 
        user0.addMusicPlaylist((-1086385980), (Music) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      User user0 = null;
      try {
        user0 = new User((User) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      PlanFree planFree0 = new PlanFree();
      LinkedList<MusicReproduction> linkedList0 = new LinkedList<MusicReproduction>();
      User user0 = null;
      try {
        user0 = new User("}S&b?.yY&=,C[qVmP>\"", "}S&b?.yY&=,C[qVmP>\"", "}S&b?.yY&=,C[qVmP>\"", "}S&b?.yY&=,C[qVmP>\"", planFree0, (List<Playlist>) null, linkedList0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      User user0 = new User("S\u00F3 o autor da playlist pode adicionar m\u00FAsicas.", "org.Model.Plan.Plan", "S\u00F3 o autor da playlist pode adicionar m\u00FAsicas.", "'L`t");
      List<Playlist> list0 = user0.getPlaylists();
      LinkedList<MusicReproduction> linkedList0 = new LinkedList<MusicReproduction>();
      linkedList0.add((MusicReproduction) null);
      User user1 = new User("0R\r1{`Pq<f}v`!))", "'L`t", "'L`t", "'L`t", planPremiumBase0, list0, linkedList0);
      // Undeclared exception!
      try { 
        user1.getMusicReproductions();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      List<Playlist> list0 = List.of(playlist0, playlist0, playlist0);
      Music music0 = new Music();
      LocalDate localDate0 = MockLocalDate.now();
      MusicReproduction musicReproduction0 = new MusicReproduction(music0, localDate0);
      List<MusicReproduction> list1 = List.of(musicReproduction0, musicReproduction0, musicReproduction0);
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      PlanFree planFree0 = new PlanFree(planPremiumBase0);
      User user0 = new User("TU.Mc!{{ ;[Q`", "`KLs<0~V2?V,B", "Utilizadores Free n\u00E3o podem adicionar m\u00FAsicas a playlists.", "TU.Mc!{{ ;[Q`", planFree0, list0, list1);
      user0.getPlaylists();
      assertEquals("Utilizadores Free n\u00E3o podem adicionar m\u00FAsicas a playlists.", user0.getAdress());
      assertEquals("TU.Mc!{{ ;[Q`", user0.getPassword());
      assertEquals("TU.Mc!{{ ;[Q`", user0.getUsername());
      assertEquals("`KLs<0~V2?V,B", user0.getEmail());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      User user0 = new User();
      user0.addPlaylistToLibrary((Playlist) null);
      // Undeclared exception!
      try { 
        user0.addPlaylistToLibrary((Playlist) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      User user0 = new User("\u2022", "\u2022", "\u2022", "");
      user0.addMusicReproduction((Music) null);
      LocalDate localDate0 = MockLocalDate.ofYearDay(0, 125);
      int int0 = user0.getMusicReproductionsCount(localDate0, localDate0);
      assertEquals(0, int0);
      assertEquals("\u2022", user0.getUsername());
      assertEquals("\u2022", user0.getAdress());
      assertEquals("\u2022", user0.getEmail());
      assertEquals("", user0.getPassword());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      List<Playlist> list0 = List.of(playlist0, playlist0, playlist0);
      Music music0 = new Music();
      LocalDate localDate0 = MockLocalDate.ofEpochDay(0L);
      MusicReproduction musicReproduction0 = new MusicReproduction(music0, localDate0);
      List<MusicReproduction> list1 = List.of(musicReproduction0, musicReproduction0, musicReproduction0);
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      PlanFree planFree0 = new PlanFree(planPremiumBase0);
      User user0 = new User("TU.Mc!{{ ;[Q`", "org.Model.User.User", "Utilizadores Free n\u00E3o podem adicionar m\u00FAsicas a playlists.", "dr", planFree0, list0, list1);
      int int0 = user0.getMusicReproductionsCount(localDate0, localDate0);
      assertEquals("dr", user0.getPassword());
      assertEquals("Utilizadores Free n\u00E3o podem adicionar m\u00FAsicas a playlists.", user0.getAdress());
      assertEquals("org.Model.User.User", user0.getEmail());
      assertEquals(0, int0);
      assertEquals("TU.Mc!{{ ;[Q`", user0.getUsername());
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      List<Music> list0 = playlist0.getMusics();
      Playlist playlist1 = new Playlist("TU.Mc!{{ ;[Q`", "`KLs<0~V2?V,B", list0);
      List<Playlist> list1 = List.of(playlist1, playlist1, playlist0);
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      PlanFree planFree0 = new PlanFree(planPremiumBase0);
      LinkedList<MusicReproduction> linkedList0 = new LinkedList<MusicReproduction>();
      User user0 = new User("`KLs<0~V2?V,B", "TU.Mc!{{ ;[Q`", "Interprete: ", "`KLs<0~V2?V,B", planFree0, list1, linkedList0);
      user0.changePlaylistAutor("`KLs<0~V2?V,B");
      assertEquals("`KLs<0~V2?V,B", user0.getPassword());
      assertEquals("TU.Mc!{{ ;[Q`", user0.getEmail());
      assertEquals("Interprete: ", user0.getAdress());
      assertEquals("`KLs<0~V2?V,B", user0.getUsername());
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Playlist playlist0 = new Playlist("TU.Mc!{{ ;[Q`", "TU.Mc!{{ ;[Q`");
      List<Playlist> list0 = List.of(playlist0, playlist0, playlist0);
      Music music0 = new Music();
      LocalDate localDate0 = MockLocalDate.now();
      MusicReproduction musicReproduction0 = new MusicReproduction(music0, localDate0);
      List<MusicReproduction> list1 = List.of(musicReproduction0, musicReproduction0, musicReproduction0);
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      PlanFree planFree0 = new PlanFree(planPremiumBase0);
      User user0 = new User("TU.Mc!{{ ;[Q`", "`KLs<0~V2?V,B", "Utilizadores Free n\u00E3o podem adicionar m\u00FAsicas a playlists.", "TU.Mc!{{ ;[Q`", planFree0, list0, list1);
      int int0 = user0.getUserPlaylistCount();
      assertEquals("TU.Mc!{{ ;[Q`", user0.getPassword());
      assertEquals(3, int0);
      assertEquals("Utilizadores Free n\u00E3o podem adicionar m\u00FAsicas a playlists.", user0.getAdress());
      assertEquals("`KLs<0~V2?V,B", user0.getEmail());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      List<Playlist> list0 = List.of(playlist0, playlist0, playlist0);
      Music music0 = new Music();
      LocalDate localDate0 = MockLocalDate.now();
      MusicReproduction musicReproduction0 = new MusicReproduction(music0, localDate0);
      List<MusicReproduction> list1 = List.of(musicReproduction0, musicReproduction0, musicReproduction0);
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      PlanFree planFree0 = new PlanFree(planPremiumBase0);
      User user0 = new User("TU.Mc!{{ ;[Q`", "`KLs<0~V2?V,B", "Utilizadores Free n\u00E3o podem adicionar m\u00FAsicas a playlists.", "TU.Mc!{{ ;[Q`", planFree0, list0, list1);
      int int0 = user0.getUserPlaylistCount();
      assertEquals(0, int0);
      assertEquals("TU.Mc!{{ ;[Q`", user0.getUsername());
      assertEquals("`KLs<0~V2?V,B", user0.getEmail());
      assertEquals("Utilizadores Free n\u00E3o podem adicionar m\u00FAsicas a playlists.", user0.getAdress());
      assertEquals("TU.Mc!{{ ;[Q`", user0.getPassword());
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      User user0 = new User();
      Playlist playlist0 = new Playlist("@", "@");
      user0.addPlaylistToLibrary(playlist0);
      try { 
        user0.removeMusicFromPlaylist((Music) null, 0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o tem permiss\u00E3o para aceder a este recurso: S\u00F3 o autor da playlist pode remover m\u00FAsicas.
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      Playlist playlist1 = new Playlist("TU.Mc!{{ ;[Q`", "TU.Mc!{{ ;[Q`");
      List<Music> list0 = playlist0.getMusics();
      Playlist playlist2 = new Playlist("TU.Mc!{{ ;[Q`", "`KLs<0~V2?V,B", list0);
      List<Playlist> list1 = List.of(playlist2, playlist2, playlist1);
      Music music0 = new Music();
      LocalDate localDate0 = MockLocalDate.now();
      MusicReproduction musicReproduction0 = new MusicReproduction(music0, localDate0);
      List<MusicReproduction> list2 = List.of(musicReproduction0, musicReproduction0, musicReproduction0);
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      PlanFree planFree0 = new PlanFree(planPremiumBase0);
      User user0 = new User("TU.Mc!{{ ;[Q`", "`KLs<0~V2?V,B", "Utilizadores Free n\u00E3o podem adicionar m\u00FAsicas a playlists.", "TU.Mc!{{ ;[Q`", planFree0, list1, list2);
      try { 
        user0.removeMusicFromPlaylist(music0, 1);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: 
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      User user0 = new User();
      Playlist playlist0 = new Playlist();
      user0.addPlaylistToLibrary(playlist0);
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop();
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase(planPremiumTop0);
      user0.setPlan(planPremiumBase0);
      try { 
        user0.getPlaylistById(100);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: 100
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      User user0 = new User();
      // Undeclared exception!
      try { 
        user0.getPlaylistById((-1));
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Utilizadores Free n\u00E3o podem adicionar m\u00FAsicas a playlists.
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      User user0 = new User();
      Playlist playlist0 = new Playlist();
      user0.addPlaylistToLibrary(playlist0);
      Music music0 = new Music();
      try { 
        user0.addMusicPlaylist(2336, music0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: 2336
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      User user0 = new User("D", "D", "D", "D");
      Playlist playlist0 = new Playlist("D", "D");
      user0.addPlaylistToLibrary(playlist0);
      Music music0 = new Music();
      user0.addMusicPlaylist(0, music0);
      user0.removeMusicFromPlaylist(music0, 0);
      assertEquals("D", user0.getUsername());
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop();
      User user0 = new User();
      List<Playlist> list0 = user0.getPlaylists();
      List<MusicReproduction> list1 = user0.getMusicReproductions();
      User user1 = new User((String) null, (String) null, "", (String) null, planPremiumTop0, list0, list1);
      user1.addPlaylist("\u2022");
      assertEquals("", user1.getAdress());
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      User user0 = new User();
      // Undeclared exception!
      try { 
        user0.addPlaylist("O;hc/T)tzxdT/K{?&");
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Utilizadores Free n\u00E3o podem adicionar playlists.
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      User user0 = new User();
      Playlist playlist0 = new Playlist();
      user0.addPlaylistToLibrary(playlist0);
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop();
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase(planPremiumTop0);
      user0.setPlan(planPremiumBase0);
      String string0 = user0.namePlaylists();
      assertEquals("\uD83C\uDFB5 [#000]                           | Autor:                \n", string0);
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      User user0 = new User();
      // Undeclared exception!
      try { 
        user0.namePlaylists();
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Utilizadores Free n\u00E3o possuem playlists.
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      User user0 = new User("\u2022", "\u2022", "\u2022", "");
      User user1 = new User("\u2022", "\u2022", "", "\u2022");
      boolean boolean0 = user1.equals(user0);
      assertEquals("\u2022", user1.getUsername());
      assertEquals("\u2022", user0.getEmail());
      assertEquals("", user0.getPassword());
      assertEquals("\u2022", user1.getEmail());
      assertEquals("", user1.getAdress());
      assertEquals("\u2022", user0.getUsername());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      User user0 = new User("q", "q", "q", "q");
      User user1 = new User();
      user1.setUsername("q");
      boolean boolean0 = user1.equals(user0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      User user0 = new User("q", "q", "q", "q");
      User user1 = new User();
      boolean boolean0 = user1.equals(user0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      User user0 = new User("|Mo)#Elr:sq", "rA:", "p\u2022", "\uD83C\uDFB5 [#%03d] %-25s | Autor: %-15s\n");
      Object object0 = new Object();
      boolean boolean0 = user0.equals(object0);
      assertEquals("\uD83C\uDFB5 [#%03d] %-25s | Autor: %-15s\n", user0.getPassword());
      assertFalse(boolean0);
      assertEquals("rA:", user0.getEmail());
      assertEquals("|Mo)#Elr:sq", user0.getUsername());
      assertEquals("p\u2022", user0.getAdress());
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      User user0 = new User();
      boolean boolean0 = user0.equals(user0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      User user0 = new User();
      User user1 = new User(user0);
      boolean boolean0 = user1.equals(user0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      User user0 = new User();
      Music music0 = new Music();
      MusicReproduction musicReproduction0 = new MusicReproduction(music0);
      List<MusicReproduction> list0 = List.of(musicReproduction0, musicReproduction0, musicReproduction0, musicReproduction0, musicReproduction0, musicReproduction0, musicReproduction0, musicReproduction0);
      user0.setMusicReproductions(list0);
      assertEquals("", user0.getAdress());
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      User user0 = new User();
      Playlist playlist0 = new Playlist();
      List<Playlist> list0 = List.of(playlist0, playlist0, playlist0, playlist0, playlist0, playlist0, playlist0);
      user0.setPlaylists(list0);
      assertEquals("", user0.getAdress());
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      User user0 = new User();
      user0.setEmail("\u2554\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550 DADOS DO UTILIZADOR \u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2557\n  \uD83D\uDC64 Nome de Utilizador: \n  \uD83D\uDCE7 Email: \n  \uD83C\uDFE0 Morada: \n  \uD83D\uDD11 Password: \n  \uD83D\uDCCB Plano: Plano: Free\n    Pontos: 0\n\u255A\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u255D");
      assertEquals("", user0.getPassword());
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      User user0 = new User("_nw>($", "SvCazJ>uGs5m'", "", "_nw>($");
      String string0 = user0.getEmail();
      assertEquals("_nw>($", user0.getPassword());
      assertEquals("SvCazJ>uGs5m'", string0);
      assertEquals("_nw>($", user0.getUsername());
      assertEquals("", user0.getAdress());
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      User user0 = new User();
      User user1 = user0.clone();
      assertEquals("", user1.getUsername());
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      User user0 = new User();
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop();
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase(planPremiumTop0);
      user0.setPlan(planPremiumBase0);
      String string0 = user0.namePlaylists();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      User user0 = new User();
      String string0 = user0.toString();
      assertEquals("\u2554\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550 DADOS DO UTILIZADOR \u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2557\n  \uD83D\uDC64 Nome de Utilizador: \n  \uD83D\uDCE7 Email: \n  \uD83C\uDFE0 Morada: \n  \uD83D\uDD11 Password: \n  \uD83D\uDCCB Plano: Plano: Free\n    Pontos: 0\n\u255A\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u255D", string0);
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      User user0 = new User("QhUjfH|0q(", "org.Model.User.User", "[+oT:N^b+--@<a~>", (String) null);
      String string0 = user0.getPassword();
      assertEquals("[+oT:N^b+--@<a~>", user0.getAdress());
      assertEquals("QhUjfH|0q(", user0.getUsername());
      assertNull(string0);
      assertEquals("org.Model.User.User", user0.getEmail());
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      User user0 = new User("I", "I", "I", "I");
      Music music0 = new Music();
      user0.addMusicReproduction(music0);
      // Undeclared exception!
      try { 
        user0.getMusicReproductionsCount((LocalDate) null, (LocalDate) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.time.chrono.ChronoLocalDate", e);
      }
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      Playlist playlist0 = new Playlist();
      List<Playlist> list0 = List.of(playlist0, playlist0, playlist0);
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      PlanFree planFree0 = new PlanFree(planPremiumBase0);
      LinkedList<MusicReproduction> linkedList0 = new LinkedList<MusicReproduction>();
      User user0 = new User("`KLs<0~V2?V,B", "TU.Mc!{{ ;[Q`", "Interprete: ", "`KLs<0~V2?V,B", planFree0, list0, linkedList0);
      String string0 = user0.getUsername();
      assertEquals("Interprete: ", user0.getAdress());
      assertEquals("TU.Mc!{{ ;[Q`", user0.getEmail());
      assertEquals("`KLs<0~V2?V,B", string0);
      assertEquals("`KLs<0~V2?V,B", user0.getPassword());
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      User user0 = new User("A", "A", "A", "A");
      boolean boolean0 = user0.hasLibrary();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      User user0 = new User("|Mo)#Elr:sq", "rA:", "p\u2022", "\uD83C\uDFB5 [#%03d] %-25s | Autor: %-15s\n");
      user0.getPlan();
      assertEquals("\uD83C\uDFB5 [#%03d] %-25s | Autor: %-15s\n", user0.getPassword());
      assertEquals("p\u2022", user0.getAdress());
      assertEquals("|Mo)#Elr:sq", user0.getUsername());
      assertEquals("rA:", user0.getEmail());
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      User user0 = new User();
      String string0 = user0.getAdress();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test74()  throws Throwable  {
      User user0 = new User();
      user0.addPoints();
      assertEquals("", user0.getPassword());
  }

  @Test(timeout = 4000)
  public void test75()  throws Throwable  {
      User user0 = new User();
      user0.setPassword("8pN@!x:6[3:J)S`ivL");
      assertEquals("8pN@!x:6[3:J)S`ivL", user0.getPassword());
  }
}
