/*
 * This file was automatically generated by EvoSuite
 * Mon May 04 17:37:09 GMT 2026
 */

package org.Model;
import java.util.Arrays;

import org.junit.Test;
import org.junit.Ignore;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.LocalDate;
import java.time.Period;
import java.time.chrono.IsoChronology;
import java.util.Collection;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import org.Model.Album.Album;
import org.Model.Music.Music;
import org.Model.Music.MusicReproduction;
import org.Model.Plan.PlanFree;
import org.Model.Plan.PlanPremiumBase;
import org.Model.Plan.PlanPremiumTop;
import org.Model.Playlist.Playlist;
import org.Model.Playlist.PlaylistFavorites;
import org.Model.Playlist.PlaylistRandom;
import org.Model.User.User;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
import org.evosuite.runtime.mock.java.time.chrono.MockIsoChronology;
public class SpotifUM_ESTest {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      LocalDate localDate0 = MockLocalDate.now();
      try { 
        spotifUM0.getUserWithMostReproductions(localDate0, (LocalDate) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o existem utilizadores na base de dados.
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.incrementGenreReproductions("jTlkJ#=FR&=F");
      spotifUM0.incrementGenreReproductions("}PNE9}F%7~;;}zFbe\"\"");
      String string0 = spotifUM0.getGenreWithMostReproductions();
      assertEquals("jTlkJ#=FR&=F", string0);
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.addNewMusic((String) null, "\n", ">{^sRY?!1P;k2", "\n", "\n", (String) null, "\n", 287, false, "\n");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.addNewMusic("org.Model.Music.Music", "Eminem", "Iw9$'s (.", "}i]KfUt", "}i]KfUt", "org.Model.Music.Music", "", 320, true, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      try { 
        spotifUM0.addNewMusic("God's Plan", (String) null, "&W:j`^{h", "N\u00E3o existem utilizadores na base de dados.", "G_lUl#-`aCIX<2G]+ ", "W_LVv2`/<:\",a47E-", (String) null, 3571, false, "^");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // J\u00E1 existe: God's Plan
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.addNewUser((String) null, "YbS8+iR'9+BHE,F+A:", "YbS8+iR'9+BHE,F+A:", (String) null);
      assertEquals(0, spotifUM0.getPublicPlaylistSize());
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.addNewUser("gG|", "gG|", "gG|", "gG|");
      try { 
        spotifUM0.authenticateUser("gG|", "Top Dawg");
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Password incorreta.
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.authenticateUser("gG|", "Top Dawg");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: gG|
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      HashMap<Integer, Playlist> hashMap1 = new HashMap<Integer, Playlist>();
      HashMap<String, User> hashMap2 = new HashMap<String, User>();
      HashMap<String, Album> hashMap3 = new HashMap<String, Album>();
      SpotifUM spotifUM0 = new SpotifUM();
      Map<String, Integer> map0 = spotifUM0.getGenreReproductions();
      HashMap<String, Integer> hashMap4 = new HashMap<String, Integer>();
      SpotifUM spotifUM1 = new SpotifUM(hashMap0, hashMap1, hashMap2, hashMap3, map0, hashMap4);
      assertTrue(spotifUM1.equals((Object)spotifUM0));
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      HashMap<Integer, Playlist> hashMap0 = new HashMap<Integer, Playlist>();
      spotifUM0.setPublicPlaylists(hashMap0);
      assertEquals("SpotifUM(...)", spotifUM0.toString());
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      HashMap<String, Integer> hashMap0 = new HashMap<String, Integer>();
      spotifUM0.setGenreReproductions(hashMap0);
      assertTrue(hashMap0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = spotifUM0.getUserWithMostReproductions();
      spotifUM0.setCurrentUser(user0);
      spotifUM0.setCurrentUserUsername("ns(`0l*dw/v)5");
      assertEquals("SpotifUM(...)", spotifUM0.toString());
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = spotifUM0.getUserWithMostReproductions();
      spotifUM0.setCurrentUser(user0);
      spotifUM0.setCurrentUserPassword("Los Angeles");
      assertEquals(6, spotifUM0.getPublicPlaylistSize());
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      PlanFree planFree0 = new PlanFree();
      Playlist playlist0 = new Playlist();
      List<Playlist> list0 = Arrays.asList(playlist0);
      List<MusicReproduction> list1 = Arrays.asList();
      User user0 = new User("ZlwY86JKt>V-", "ZlwY86JKt>V-", "ZlwY86JKt>V-", "", planFree0, list0, list1);
      spotifUM0.setCurrentUser(user0);
      spotifUM0.setCurrentUserEmail("amq@@Ve$CO0O.tn");
      assertEquals("SpotifUM(...)", spotifUM0.toString());
  }
@Ignore("EvoSuite: Mockito/ByteBuddy mock failure")
@Test(timeout = 4000)
public void test014()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      MusicReproduction musicReproduction0 = mock(MusicReproduction.class, new ViolatedAssumptionAnswer());
      List<MusicReproduction> list0 = Arrays.asList(musicReproduction0, musicReproduction0, musicReproduction0, musicReproduction0, musicReproduction0, musicReproduction0);
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      User user0 = new User("G=ZsP)2*", "G=ZsP)2*", "G=ZsP)2*", "God's Plan", planPremiumBase0, linkedList0, list0);
      spotifUM0.setCurrentUser(user0);
      spotifUM0.addToCurrentUserPlaylist("G=ZsP)2*");
      assertEquals(0, spotifUM0.getPublicPlaylistSize());
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = spotifUM0.getUserWithMostPoints();
      spotifUM0.setCurrentUser(user0);
      spotifUM0.addToCurrentUserMusicReproductions("il^hu/$)bZONA");
      assertEquals("SpotifUM(...)", spotifUM0.toString());
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = spotifUM0.getUserWithMostReproductions();
      spotifUM0.setCurrentUser(user0);
      spotifUM0.addPointsToCurrentUser();
      assertEquals(6, spotifUM0.getPublicPlaylistSize());
  }
@Ignore("EvoSuite: requires seeded playlists")
@Test(timeout = 4000)
public void test017()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      User user0 = new User();
      spotifUM0.setCurrentUser(user0);
      spotifUM0.populateDatabase();
      spotifUM0.addPlaylistToCurrentUserLibrary(5);
      assertEquals(6, spotifUM0.getPublicPlaylistSize());
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      spotifUM0.addNewMusic(";KWIKS^ze5?", "God's Plan", "Discovery", "God's Plan", "Sim", "simao", "Discovery", (-738), true, (String) null);
      assertEquals(6, spotifUM0.getPublicPlaylistSize());
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      String string0 = spotifUM0.playMusic("God's Plan");
      assertEquals("Yeah, they wishin' and wishin' and wishin' and wishin'\nThey wishin' on me, yuh\nI been movin' calm, don't start no trouble", string0);
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Music music0 = new Music();
      music0.play();
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      hashMap0.put("Msicas:\n", music0);
      spotifUM0.setMusics(hashMap0);
      Music music1 = spotifUM0.mostReproducedMusic();
      assertEquals("", music1.getMusicalFigures());
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      Music music0 = new Music();
      music0.setReproductions((-1189737368));
      hashMap0.put("dbD?tZ", music0);
      spotifUM0.setMusics(hashMap0);
      Music music1 = spotifUM0.mostReproducedMusic();
      assertNotSame(music1, music0);
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Music music0 = new Music();
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      hashMap0.put("Msicas:\n", music0);
      spotifUM0.setMusics(hashMap0);
      Music music1 = spotifUM0.mostReproducedMusic();
      assertEquals("", music1.getMusicalFigures());
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      Music music0 = spotifUM0.mostReproducedMusic();
      assertEquals("Synth", music0.getMusicalFigures());
      assertEquals("If you wanna run away with me, I know a galaxy\nAnd I can take you for a ride\nI had a premonition that we fell into a rhythm", music0.getLyrics());
      assertEquals(203, music0.getDuration());
      assertEquals("Pop", music0.getGenre());
      assertEquals("Warner", music0.getPublisher());
      assertEquals("Dua Lipa", music0.getInterpreter());
      assertEquals("Future Nostalgia", music0.getAlbum());
      assertEquals("Levitating", music0.getName());
  }
@Ignore("EvoSuite: depends on playlist order")
@Test(timeout = 4000)
public void test024()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Playlist playlist0 = new Playlist("~R{1QbzP$@&RB:", "~R{1QbzP$@&RB:");
      List<Playlist> list0 = Arrays.asList(playlist0);
      List<MusicReproduction> list1 = Arrays.asList();
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      User user0 = new User("9<?=f", "One More Time", "~R{1QbzP$@&RB:", "9<?=f", planPremiumBase0, list0, list1);
      spotifUM0.setCurrentUser(user0);
      String string0 = spotifUM0.listCurrentUserPlaylists();
      assertEquals("\uD83C\uDFB5 [#000] ~R{1QbzP$@&RB:            | Autor: ~R{1QbzP$@&RB: \n", string0);
  }
@Ignore("EvoSuite: Mockito/ByteBuddy mock failure")
@Test(timeout = 4000)
public void test025()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      MusicReproduction musicReproduction0 = mock(MusicReproduction.class, new ViolatedAssumptionAnswer());
      List<MusicReproduction> list0 = Arrays.asList(musicReproduction0, musicReproduction0, musicReproduction0, musicReproduction0, musicReproduction0, musicReproduction0);
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      User user0 = new User("G=ZsP)2*", "G=ZsP)2*", "G=ZsP)2*", "God's Plan", planPremiumBase0, linkedList0, list0);
      spotifUM0.setCurrentUser(user0);
      String string0 = spotifUM0.listCurrentUserPlaylists();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Playlist playlist0 = new Playlist("~R{1QbzP$@&RB:", "~R{1QbzP$@&RB:");
      List<Playlist> list0 = Arrays.asList(playlist0);
      List<MusicReproduction> list1 = Arrays.asList();
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      User user0 = new User("9<?=f", "One More Time", "~R{1QbzP$@&RB:", "9<?=f", planPremiumBase0, list0, list1);
      spotifUM0.setCurrentUser(user0);
      String string0 = spotifUM0.listAllMusicsInPlaylist(965);
      assertEquals("N\u00E3o encontrado: 965", string0);
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      String string0 = spotifUM0.listAllMusics();
      assertEquals("\uD83C\uDFB6 Levitating \u2014 Dua Lipa\n\uD83C\uDFB6 Sweet Child O' Mine \u2014 Guns N' Roses\n\uD83C\uDFB6 Rap God \u2014 Eminem\n\uD83C\uDFB6 Bohemian Rhapsody \u2014 Queen\n\uD83C\uDFB6 Billie Jean \u2014 Michael Jackson\n\uD83C\uDFB6 Don't Start Now \u2014 Dua Lipa\n\uD83C\uDFB6 Blinding Lights \u2014 The Weeknd\n\uD83C\uDFB6 Hino do Futebol Clube do Porto \u2014 Maria Am\u00E9lia Canossa\n\uD83C\uDFB6 Shape of You \u2014 Ed Sheeran\n\uD83C\uDFB6 One More Time \u2014 Daft Punk\n\uD83C\uDFB6 Hotel California \u2014 Eagles\n\uD83C\uDFB6 Beat It \u2014 Michael Jackson\n\uD83C\uDFB6 Stairway to Heaven \u2014 Led Zeppelin\n\uD83C\uDFB6 Never Gonna Give You Up \u2014 Rick Astley\n\uD83C\uDFB6 God's Plan \u2014 Drake\n\uD83C\uDFB6 Titanium \u2014 David Guetta\n\uD83C\uDFB6 SICKO MODE \u2014 Travis Scott\n\uD83C\uDFB6 Starboy \u2014 The Weeknd\n\uD83C\uDFB6 HUMBLE. \u2014 Kendrick Lamar\n\uD83C\uDFB6 Watermelon Sugar \u2014 Harry Styles\n\uD83C\uDFB6 Smells Like Teen Spirit \u2014 Nirvana\n", string0);
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      User user0 = new User("Gbd's@Pn", "Gbd's@Pn", "Gbd's@Pn", "Gbd's@Pn");
      spotifUM0.setCurrentUser(user0);
      boolean boolean0 = spotifUM0.isPasswordCorrect("Gbd's@Pn");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedHashSet<Playlist> linkedHashSet0 = new LinkedHashSet<Playlist>();
      List<Playlist> list0 = List.copyOf((Collection<? extends Playlist>) linkedHashSet0);
      LinkedList<MusicReproduction> linkedList0 = new LinkedList<MusicReproduction>();
      User user0 = new User("ln!mk=g#0y", (String) null, " Z(ESw=TA1", "ln!mk=g#0y", planPremiumBase0, list0, linkedList0);
      spotifUM0.setCurrentUser(user0);
      boolean boolean0 = spotifUM0.isPasswordCorrect((String) null);
      assertFalse(boolean0);
  }
@Ignore("EvoSuite: Mockito/ByteBuddy mock failure")
@Test(timeout = 4000)
public void test030()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      MusicReproduction musicReproduction0 = mock(MusicReproduction.class, new ViolatedAssumptionAnswer());
      List<MusicReproduction> list0 = Arrays.asList(musicReproduction0, musicReproduction0, musicReproduction0, musicReproduction0, musicReproduction0, musicReproduction0);
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      User user0 = new User("G=ZsP)2*", "G=ZsP)2*", "G=ZsP)2*", "God's Plan", planPremiumBase0, linkedList0, list0);
      spotifUM0.setCurrentUser(user0);
      boolean boolean0 = spotifUM0.hasLibrary();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      User user0 = new User("Gbd's@Pn", "Gbd's@Pn", "Gbd's@Pn", "Gbd's@Pn");
      spotifUM0.setCurrentUser(user0);
      boolean boolean0 = spotifUM0.hasLibrary();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      Map<String, User> map0 = spotifUM0.getUsers();
      assertEquals(3, map0.size());
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = spotifUM0.getUserWithMostPlaylists();
      assertEquals("root", user0.getPassword());
  }
@Ignore("EvoSuite: depends on playlist count/order")
@Test(timeout = 4000)
public void test034()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      PlaylistRandom playlistRandom0 = spotifUM0.getRandomPlaylist();
      assertEquals("Playlist Aleat\u00F3ria com 1 m\u00FAsicas.", playlistRandom0.getName());
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      Map<Integer, Playlist> map0 = spotifUM0.getPublicPlaylists();
      assertEquals(6, map0.size());
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      int int0 = spotifUM0.getPublicPlaylistSize();
      assertEquals(6, int0);
  }
@Ignore("EvoSuite: requires seeded playlists")
@Test(timeout = 4000)
public void test037()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      Playlist playlist0 = spotifUM0.getPublicPlaylistById(0);
      assertEquals("Spotify", playlist0.getAutor());
  }
@Ignore("EvoSuite: requires seeded playlists")
@Test(timeout = 4000)
public void test038()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      Playlist playlist0 = spotifUM0.getPublicPlaylistById(1);
      assertEquals(1, playlist0.getId());
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      Map<String, Music> map0 = spotifUM0.getMusics();
      assertEquals(21, map0.size());
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.incrementGenreReproductions("");
      String string0 = spotifUM0.getGenreWithMostReproductions();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.incrementGenreReproductions("q");
      Map<String, Integer> map0 = spotifUM0.getGenreReproductions();
      assertEquals(1, map0.size());
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      User user0 = new User("Gbd's@Pn", "Gbd's@Pn", "Gbd's@Pn", "Gbd's@Pn");
      spotifUM0.setCurrentUser(user0);
      String string0 = spotifUM0.getCurrentUserPlanName();
      assertEquals("Free", string0);
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      User user0 = new User("Gbd's@Pg", "Gbd's@Pg", "Gbd's@Pg", "Gbd's@Pg");
      spotifUM0.setCurrentUser(user0);
      User user1 = spotifUM0.getCurrentUser();
      assertEquals("Gbd's@Pg", user1.getEmail());
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.incrementArtistReproductions("");
      Map<String, Integer> map0 = spotifUM0.getArtistReproductions();
      assertFalse(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.addNewAlbum("Ddi:aXj!_W^t*mjwc", "S\u00F3 o autor da playlist pode adicionar m\u00FAsicas.");
      Map<String, Album> map0 = spotifUM0.getAlbums();
      assertFalse(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      User user0 = new User("f<>fei+CAgiub8;_", "f<>fei+CAgiub8;_", "f<>fei+CAgiub8;_", "n?~X1PvS!wm4H1c");
      spotifUM0.setCurrentUser(user0);
      boolean boolean0 = spotifUM0.currentUserAccessToFavorites();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      User user0 = new User("XO>D)+5]'s.x", "org.Exceptions.NoMusicsInDatabaseException", "org.Exceptions.NoMusicsInDatabaseException", "XO>D)+5]'s.x");
      spotifUM0.setCurrentUser(user0);
      PlaylistFavorites playlistFavorites0 = spotifUM0.createFavoritesPlaylist((-241), true);
      assertEquals("SpotifyUM", playlistFavorites0.getAutor());
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedHashSet<Playlist> linkedHashSet0 = new LinkedHashSet<Playlist>();
      List<Playlist> list0 = List.copyOf((Collection<? extends Playlist>) linkedHashSet0);
      LinkedList<MusicReproduction> linkedList0 = new LinkedList<MusicReproduction>();
      User user0 = new User("dnz<mk=g>#0y", (String) null, " Z(ESw=TA1", "bqSb:0!RUCys>", planPremiumBase0, list0, linkedList0);
      spotifUM0.setCurrentUser(user0);
      boolean boolean0 = spotifUM0.canCurrentUserSkip();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      PlanFree planFree0 = new PlanFree();
      Playlist playlist0 = new Playlist();
      List<Playlist> list0 = Arrays.asList(playlist0);
      List<MusicReproduction> list1 = Arrays.asList();
      User user0 = new User("ZlwY86JKt>V-", "ZlwY86JKt>V-", "ZlwY86JKt>V-", "", planFree0, list0, list1);
      spotifUM0.setCurrentUser(user0);
      boolean boolean0 = spotifUM0.canCurrentUserSkip();
      assertFalse(boolean0);
  }
@Ignore("EvoSuite: Mockito/ByteBuddy mock failure")
@Test(timeout = 4000)
public void test050()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      MusicReproduction musicReproduction0 = mock(MusicReproduction.class, new ViolatedAssumptionAnswer());
      List<MusicReproduction> list0 = Arrays.asList(musicReproduction0, musicReproduction0, musicReproduction0, musicReproduction0, musicReproduction0, musicReproduction0);
      LinkedList<Playlist> linkedList0 = new LinkedList<Playlist>();
      User user0 = new User("G=ZsP)2*", "G=ZsP)2*", "G=ZsP)2*", "God's Plan", planPremiumBase0, linkedList0, list0);
      spotifUM0.setCurrentUser(user0);
      boolean boolean0 = spotifUM0.canCurrentUserChooseWhatToPlay();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      User user0 = new User("Gbd's@Pn", "Gbd's@Pn", "Gbd's@Pn", "Gbd's@Pn");
      spotifUM0.setCurrentUser(user0);
      boolean boolean0 = spotifUM0.canCurrentUserChooseWhatToPlay();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      PlanPremiumTop planPremiumTop0 = new PlanPremiumTop();
      User user0 = new User();
      List<Playlist> list0 = user0.getPlaylists();
      List<MusicReproduction> list1 = user0.getMusicReproductions();
      User user1 = new User("ju>lW@l8wH_'ir?<U8", "ju>lW@l8wH_'ir?<U8", "ju>lW@l8wH_'ir?<U8", "ju>lW@l8wH_'ir?<U8", planPremiumTop0, list0, list1);
      spotifUM0.setCurrentUser(user1);
      try { 
        spotifUM0.setPlaylistAsPublic((-1885207704));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: -1885207704
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      User user0 = new User();
      spotifUM0.setCurrentUser(user0);
      // Undeclared exception!
      try { 
        spotifUM0.setPlaylistAsPublic(2997);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Utilizadores Free n\u00E3o podem adicionar m\u00FAsicas a playlists.
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setPlaylistAsPublic(1006);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setMusics((Map<String, Music>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.HashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setArtistReproductions((Map<String, Integer>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.HashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      hashMap0.put("IGvC$G/C*Hu{T3", (Music) null);
      spotifUM0.setMusics(hashMap0);
      // Undeclared exception!
      try { 
        spotifUM0.mostReproducedMusic();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      User user0 = new User();
      spotifUM0.setCurrentUser(user0);
      // Undeclared exception!
      try { 
        spotifUM0.listCurrentUserPlaylists();
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Utilizadores Free n\u00E3o possuem playlists.
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      User user0 = new User();
      spotifUM0.setCurrentUser(user0);
      // Undeclared exception!
      try { 
        spotifUM0.listAllMusicsInPlaylist((-1994091956));
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Utilizadores Free n\u00E3o podem adicionar m\u00FAsicas a playlists.
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.listAllMusicsInPlaylist(39);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.incrementGenreReproductions((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.TreeMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.incrementArtistReproductions((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.TreeMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      hashMap0.put("'_j~Y0jc430_&%Yi\"", (User) null);
      spotifUM0.setUsers(hashMap0);
      // Undeclared exception!
      try { 
        spotifUM0.getUserWithMostReproductions();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      hashMap0.put("'_j~Y0jc430_&%Yi\"", (User) null);
      spotifUM0.setUsers(hashMap0);
      // Undeclared exception!
      try { 
        spotifUM0.getUserWithMostPoints();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      User user0 = new User();
      spotifUM0.setCurrentUser(user0);
      // Undeclared exception!
      try { 
        spotifUM0.getUserPlaylistById((-1385));
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Utilizadores Free n\u00E3o podem adicionar m\u00FAsicas a playlists.
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      LinkedHashSet<Playlist> linkedHashSet0 = new LinkedHashSet<Playlist>();
      List<Playlist> list0 = List.copyOf((Collection<? extends Playlist>) linkedHashSet0);
      LinkedList<MusicReproduction> linkedList0 = new LinkedList<MusicReproduction>();
      User user0 = new User("ln!mk=g#0y", (String) null, " Z(ESw=TA1", "ln!mk=g#0y", planPremiumBase0, list0, linkedList0);
      spotifUM0.setCurrentUser(user0);
      // Undeclared exception!
      try { 
        spotifUM0.getUserPlaylistById(351);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // org.evosuite.runtime.mock.java.lang.MockThrowable
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      HashMap<String, Integer> hashMap0 = new HashMap<String, Integer>();
      hashMap0.put("N\u00E3o existem artistas na base de dados.", (Integer) null);
      hashMap0.put("q", (Integer) null);
      spotifUM0.setArtistReproductions(hashMap0);
      // Undeclared exception!
      try { 
        spotifUM0.getTopArtistName();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      User user0 = new User("FPkkwi:I`5~<#i,j}?*", "WnuIh#rfN6", "cY?fk,M.)}_A..", "vv52fmDB");
      spotifUM0.setCurrentUser(user0);
      // Undeclared exception!
      try { 
        spotifUM0.createGenrePlaylist("Feito para Voc\u00EA", "org.Model.User.User", 177);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // N\u00E3o existem m\u00FAsicas desse g\u00E9nero.
         //
         verifyException("org.Model.Playlist.PlaylistCreator", e);
      }
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.changeCurrentUserName("+L[ISV'vV-=#T*IB$");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.addNewUser((String) null, (String) null, (String) null, (String) null);
      // Undeclared exception!
      try { 
        spotifUM0.authenticateUser((String) null, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      User user0 = new User();
      spotifUM0.setCurrentUser(user0);
      // Undeclared exception!
      try { 
        spotifUM0.addToCurrentUserPlaylist("Reproducoes: ");
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Utilizadores Free n\u00E3o podem adicionar playlists.
         //
         verifyException("org.Model.User.User", e);
      }
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      try {
                new SpotifUM((SpotifUM) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      HashMap<String, User> hashMap1 = new HashMap<String, User>();
      HashMap<String, Integer> hashMap2 = new HashMap<String, Integer>();
      try {
                new SpotifUM(hashMap0, (Map<Integer, Playlist>) null, hashMap1, (Map<String, Album>) null, hashMap2, hashMap2);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      boolean boolean0 = spotifUM0.musicExists("U}>`|A7P%");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Map<Integer, Playlist> map0 = spotifUM0.getPublicPlaylists();
      assertTrue(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      User user0 = spotifUM0.getCurrentUser();
      assertNull(user0);
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Map<String, Integer> map0 = spotifUM0.getArtistReproductions();
      assertTrue(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Map<String, Music> map0 = spotifUM0.getMusics();
      assertEquals(0, map0.size());
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Map<String, Album> map0 = spotifUM0.getAlbums();
      spotifUM0.setAlbums(map0);
      assertEquals(0, spotifUM0.getPublicPlaylistSize());
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      SpotifUM spotifUM1 = new SpotifUM(spotifUM0);
      boolean boolean0 = spotifUM0.equals(spotifUM1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      SpotifUM spotifUM1 = new SpotifUM();
      boolean boolean0 = spotifUM1.equals(spotifUM0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      boolean boolean0 = spotifUM0.equals("Tastes like strawberries on a summer evening\nAnd it sounds just like a song\nI want more berries and that summer feeling");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      boolean boolean0 = spotifUM0.equals(spotifUM0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      SpotifUM spotifUM1 = new SpotifUM();
      boolean boolean0 = spotifUM1.equals(spotifUM0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.getUserWithMostReproductions();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o existem utilizadores na base de dados.
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Period period0 = Period.ofYears((-2087831322));
      IsoChronology isoChronology0 = period0.getChronology();
      LocalDate localDate0 = MockIsoChronology.dateNow(isoChronology0);
      try { 
        spotifUM0.getUserWithMostReproductions(localDate0, localDate0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o existem utilizadores na base de dados.
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.getUserWithMostPlaylists();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o existem utilizadores na base de dados.
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      hashMap0.put("'_j~Y0jc430_&%Yi\"", (User) null);
      spotifUM0.setUsers(hashMap0);
      // Undeclared exception!
      try { 
        spotifUM0.getUserWithMostPlaylists();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.getGenreWithMostReproductions();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o existem reprodu\u00E7\u00F5es na base de dados.
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.getUserWithMostPoints();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o existem utilizadores na base de dados.
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.addNewUser("+o'C/IZ", "+o'C/IZ", "Bq@oe", "God's Plan");
      User user0 = spotifUM0.getUserWithMostPoints();
      assertEquals("+o'C/IZ", user0.getUsername());
      assertEquals("God's Plan", user0.getPassword());
      assertEquals("Bq@oe", user0.getAdress());
      assertEquals("+o'C/IZ", user0.getEmail());
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.getTopArtistName();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o existem artistas na base de dados.
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.mostReproducedMusic();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o existem m\u00FAsicas na base de dados.
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      Music music0 = new Music("God's Plan", "L=0#AYp", "~m9_/#H!o=B]R57EW`h%", "God's Plan", (String) null, "~m9_/#H!o=B]R57EW`h%", (String) null, (-180), true);
      hashMap0.put("~m9_/#H!o=B]R57EW`h%", music0);
      spotifUM0.setMusics(hashMap0);
      Music music1 = spotifUM0.mostReproducedMusic();
      assertTrue(music1.equals((Object)music0));
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      String string0 = spotifUM0.listAllGenres();
      assertEquals("\u2022 Electronic\n\u2022 Hino\n\u2022 Hip-Hop\n\u2022 Pop\n\u2022 Rock\n", string0);
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      hashMap0.put("Free", (Music) null);
      spotifUM0.setMusics(hashMap0);
      // Undeclared exception!
      try { 
        spotifUM0.listAllGenres();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      String string0 = spotifUM0.listAllGenres();
      assertEquals("", string0);
  }
@Ignore("EvoSuite: depends on playlist order")
@Test(timeout = 4000)
public void test098()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      String string0 = spotifUM0.listPublicPlaylists();
      assertEquals("\uD83C\uDFB5 [#000] Top Global                | Autor: Spotify        \n\uD83C\uDFB5 [#001] Rock Legends              | Autor: RockFM         \n\uD83C\uDFB5 [#002] Hip-Hop Nation            | Autor: HipHopTV       \n\uD83C\uDFB5 [#003] Electronic Vibes          | Autor: EDM.com        \n\uD83C\uDFB5 [#004] Throwback Hits            | Autor: OldiesFM       \n\uD83C\uDFB5 [#005] Portuguese Pride          | Autor: RTP            \n", string0);
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      String string0 = spotifUM0.listPublicPlaylists();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.addPlaylistToCurrentUserLibrary((-1103));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: -1103
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      try { 
        spotifUM0.addPlaylistToCurrentUserLibrary(5);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // J\u00E1 existe: 5
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      // Undeclared exception!
      try { 
        spotifUM0.addMusicToCurrentUserPlaylist(13, "God's Plan");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.addMusicToCurrentUserPlaylist(1806, "");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: 
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      PlaylistRandom playlistRandom0 = spotifUM0.getRandomPlaylist();
      assertEquals("Playlist Aleat\u00F3ria com 0 m\u00FAsicas.", playlistRandom0.getName());
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      // Undeclared exception!
      try { 
        spotifUM0.removeMusicFromPlaylist("God's Plan", (Integer) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      String string0 = spotifUM0.listAllAlbums();
      assertEquals("\uD83D\uDCC0 Future Nostalgia \u2014 Dua Lipa\n\uD83D\uDCC0 Scorpion \u2014 Drake\n\uD83D\uDCC0 Fine Line \u2014 Harry Styles\n\uD83D\uDCC0 ASTROWORLD \u2014 Travis Scott\n\uD83D\uDCC0 Discovery \u2014 Daft Punk\n\uD83D\uDCC0 DAMN. \u2014 Kendrick Lamar\n\uD83D\uDCC0 The Marshall Mathers LP 2 \u2014 Eminem\n\uD83D\uDCC0 Rick Roll \u2014 Rick Astley\n\uD83D\uDCC0 Divide \u2014 Ed Sheeran\n\uD83D\uDCC0 A Night at the Opera \u2014 Queen\n\uD83D\uDCC0 After Hours \u2014 The Weeknd\n\uD83D\uDCC0 Hotel California \u2014 Eagles\n\uD83D\uDCC0 Thriller \u2014 Michael Jackson\n\uD83D\uDCC0 Tanto Porto! \u2014 FC Porto\n\uD83D\uDCC0 Led Zeppelin IV \u2014 Led Zeppelin\n\uD83D\uDCC0 Starboy \u2014 The Weeknd\n\uD83D\uDCC0 Appetite for Destruction \u2014 Guns N' Roses\n\uD83D\uDCC0 Nothing but the Beat \u2014 David Guetta\n\uD83D\uDCC0 Nevermind \u2014 Nirvana\n", string0);
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      String string0 = spotifUM0.listAllAlbums();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      Music music0 = spotifUM0.getMusicByName("God's Plan");
      try { 
        spotifUM0.addMusicToAlbum("God's Plan", music0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: God's Plan
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test109()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      Music music0 = new Music("God's Plan", "n", ";KWIKS^ze5?", "b@,Z6\"nIWN&k", (String) null, "org.Exceptions.AlreadyExistsException", "Ixx/$%Isjk48k kKy", (-133), true);
      spotifUM0.addMusicToAlbum("Discovery", music0);
      assertEquals("n", music0.getInterpreter());
  }

  @Test(timeout = 4000)
  public void test110()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.getAlbumByName("G=ZsP)2*");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: G=ZsP)2*
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test111()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      Album album0 = spotifUM0.getAlbumByName("Appetite for Destruction");
      assertEquals("Guns N' Roses", album0.getArtist());
  }

  @Test(timeout = 4000)
  public void test112()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      boolean boolean0 = spotifUM0.albumExists("Starboy");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test113()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      boolean boolean0 = spotifUM0.albumExists("WnuIh#rfN6");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test114()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      hashMap0.put("dT14^|iM", (Music) null);
      spotifUM0.setMusics(hashMap0);
      // Undeclared exception!
      try { 
        spotifUM0.listAllMusics();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test115()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      String string0 = spotifUM0.listAllMusics();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test116()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.addNewMusic("Los Angeles", "Los Angeles", "D", "TLrZe!m", "Look, I was gonna go easy on you not to hurt your feelings\nBut I'm only going to get this one chance\nSomething's wrong, I can feel it", "TLrZe!m", "KT$1l1Z^DKO6!faKt", (-1250), true, "1EFE");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test117()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.getMusicByName("9<?=f");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: 9<?=f
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test118()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Music music0 = new Music();
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      hashMap0.put("N\u00E3o existem m\u00FAsicas na base de dados.", music0);
      spotifUM0.setMusics(hashMap0);
      Music music1 = spotifUM0.getMusicByName("N\u00E3o existem m\u00FAsicas na base de dados.");
      assertEquals("", music1.getMusicalFigures());
  }

  @Test(timeout = 4000)
  public void test119()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      try { 
        spotifUM0.playMusic("+o'C/IZ");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: +o'C/IZ
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test120()  throws Throwable  {
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      Music music0 = new Music();
      hashMap0.put("b", music0);
      HashMap<Integer, Playlist> hashMap1 = new HashMap<Integer, Playlist>();
      SpotifUM spotifUM0 = new SpotifUM();
      Map<String, User> map0 = spotifUM0.getUsers();
      HashMap<String, Album> hashMap2 = new HashMap<String, Album>();
      HashMap<String, Integer> hashMap3 = new HashMap<String, Integer>();
      SpotifUM spotifUM1 = new SpotifUM(hashMap0, hashMap1, map0, hashMap2, hashMap3, hashMap3);
      String string0 = spotifUM1.playMusic("b");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test121()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
    Integer integer0 = Integer.valueOf(216);
      try { 
        spotifUM0.removeMusicFromPlaylist(".,zV(`_O<W${9T8IRA'", integer0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // N\u00E3o encontrado: .,zV(`_O<W${9T8IRA'
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test122()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.addNewUser("g'7#z=", "g'7#z=", "g'7#z=", "g'7#z=");
      boolean boolean0 = spotifUM0.userExists("g'7#z=");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test123()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      boolean boolean0 = spotifUM0.userExists("<");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test124()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.addNewUser("AwcYX,%-QoM;Ly<I[e", "AwcYX,%-QoM;Ly<I[e", "AwcYX,%-QoM;Ly<I[e", "AwcYX,%-QoM;Ly<I[e");
      User user0 = new User();
      spotifUM0.setCurrentUser(user0);
      try { 
        spotifUM0.changeCurrentUserName("AwcYX,%-QoM;Ly<I[e");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Nome de utilizador j\u00E1 existe.
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test125()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      User user0 = new User("Gbd's@Pn", "Gbd's@Pn", "Gbd's@Pn", "Gbd's@Pn");
      spotifUM0.setCurrentUser(user0);
      try { 
        spotifUM0.changeCurrentUserName("Gbd's@Pn");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Nome de utilizador igual ao atual.
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test126()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Playlist playlist0 = new Playlist("~R{1QbzP$@&RB:", "~R{1QbzP$@&RB:");
      List<Playlist> list0 = Arrays.asList(playlist0);
      List<MusicReproduction> list1 = Arrays.asList();
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      User user0 = new User("9<?=f", "One More Time", "~R{1QbzP$@&RB:", "9<?=f", planPremiumBase0, list0, list1);
      spotifUM0.setCurrentUser(user0);
      spotifUM0.changeCurrentUserName("+oC/IZ");
      assertEquals(0, spotifUM0.getPublicPlaylistSize());
  }

  @Test(timeout = 4000)
  public void test127()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.addNewUser("N\u00E3o existem reprodu!\u00F5es na base de dados.", "N\u00E3o existem reprodu!\u00F5es na base de dados.", "N\u00E3o existem reprodu!\u00F5es na base de dados.", "N\u00E3o existem reprodu!\u00F5es na base de dados.");
      spotifUM0.authenticateUser("N\u00E3o existem reprodu!\u00F5es na base de dados.", "N\u00E3o existem reprodu!\u00F5es na base de dados.");
      PlaylistFavorites playlistFavorites0 = spotifUM0.createFavoritesPlaylist((-1103), false);
      assertEquals("Feito para Voc\u00EA", playlistFavorites0.getName());
  }

  @Test(timeout = 4000)
  public void test128()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.createFavoritesPlaylist((-1103), false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test129()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      int int0 = spotifUM0.getPublicPlaylistSize();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test130()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.addToCurrentUserMusicReproductions("il^hu/$)bZONA");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test131()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.getPublicPlaylistById(0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test132()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.getUserPlaylistById((-1385));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test133()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Playlist playlist0 = new Playlist("~R{1QbzP$@&RB:", "~R{1QbzP$@&RB:");
      List<Playlist> list0 = Arrays.asList(playlist0);
      List<MusicReproduction> list1 = Arrays.asList();
      PlanPremiumBase planPremiumBase0 = new PlanPremiumBase();
      User user0 = new User("9<?=f", "One More Time", "~R{1QbzP$@&RB:", "9<?=f", planPremiumBase0, list0, list1);
      spotifUM0.setCurrentUser(user0);
      SpotifUM spotifUM1 = new SpotifUM(spotifUM0);
      assertTrue(spotifUM1.equals((Object)spotifUM0));
  }

  @Test(timeout = 4000)
  public void test134()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.addNewUser("_K#4BPkI_", "_K#4BPkI_", "_K#4BPkI_", "_K#4BPkI_");
      SpotifUM spotifUM1 = new SpotifUM();
      boolean boolean0 = spotifUM1.equals(spotifUM0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test135()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.canCurrentUserSkip();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test136()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.createGenrePlaylist("+o'C/IZ", "+o'C/IZ", 3);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test137()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.incrementArtistReproductions("r_ga#A1lU");
      String string0 = spotifUM0.getTopArtistName();
      assertEquals("r_ga#A1lU - 1\n", string0);
  }

  @Test(timeout = 4000)
  public void test138()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setGenreReproductions((Map<String, Integer>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.HashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test139()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setCurrentUserPassword("Los Angeles");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test140()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setUsers((Map<String, User>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.HashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test141()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.getCurrentUserPlanName();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test142()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setPublicPlaylists((Map<Integer, Playlist>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.HashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test143()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.addToCurrentUserPlaylist("Reproducoes: ");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test144()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.listCurrentUserPlaylists();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test145()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      String string0 = spotifUM0.toString();
      assertEquals("SpotifUM(...)", string0);
  }

  @Test(timeout = 4000)
  public void test146()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.isPasswordCorrect("Gbd's@Pn");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test147()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setAlbums((Map<String, Album>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.HashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void test148()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.addPlaylist((String) null, "+(|}yea2K+n/(2");
      assertEquals(1, spotifUM0.getPublicPlaylistSize());
  }

  @Test(timeout = 4000)
  public void test149()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.hasLibrary();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test150()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.currentUserAccessToFavorites();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test151()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setCurrentUserUsername("ns(`0l*dw/v)5");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test152()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.setCurrentUserEmail("God'sjPlan");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test153()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.addPointsToCurrentUser();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test154()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      SpotifUM spotifUM1 = new SpotifUM(spotifUM0);
      assertTrue(spotifUM1.equals((Object)spotifUM0));
      
      spotifUM1.addPlaylist(")Q26|G_", ")Q26|G_");
      boolean boolean0 = spotifUM1.equals(spotifUM0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test155()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      // Undeclared exception!
      try { 
        spotifUM0.canCurrentUserChooseWhatToPlay();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test156()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      boolean boolean0 = spotifUM0.musicExists("God's Plan");
      assertTrue(boolean0);
  }
}
