/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon May 04 17:37:09 GMT 2026
 */

package org.Model;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class SpotifUM_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.Model.SpotifUM"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "/Users/tiagobarros/ATS_25-26/TP_ATS"); 
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/hv/nk_r8y8s5h3_qghlgw2j5zpr0000gn/T/"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(SpotifUM_ESTest_scaffolding.class.getClassLoader() ,
      "org.Model.Plan.PlanPremiumTop",
      "org.Exceptions.NotFoundException",
      "org.Exceptions.NoReproductionsInDatabaseException",
      "org.Exceptions.NoArtistsInDatabaseException",
      "org.Model.Plan.PlanPremiumBase",
      "org.Exceptions.NoMusicsInDatabaseException",
      "org.Model.SpotifUM",
      "org.Model.Plan.PlanFree",
      "org.Model.User.User",
      "org.Exceptions.EmptyPlaylistException",
      "org.Model.Playlist.PlaylistRandom",
      "org.Exceptions.NoPremissionException",
      "org.Exceptions.AlreadyExistsException",
      "org.Model.Playlist.Playlist",
      "org.Model.Music.MusicReproduction",
      "org.Model.Music.Music",
      "org.Model.Playlist.PlaylistFavorites",
      "org.Model.Album.Album",
      "org.Model.Music.MusicMultimedia",
      "org.Model.Plan.Plan",
      "org.Model.Playlist.PlaylistCreator",
      "org.Exceptions.NoUsersInDatabaseException"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("org.Model.Music.MusicReproduction", false, SpotifUM_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(SpotifUM_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.Model.SpotifUM",
      "org.Model.Music.Music",
      "org.Model.Music.MusicMultimedia",
      "org.Model.Album.Album",
      "org.Model.Playlist.Playlist",
      "org.Model.User.User",
      "org.Model.Plan.Plan",
      "org.Model.Plan.PlanPremiumBase",
      "org.Model.Plan.PlanFree",
      "org.Model.Plan.PlanPremiumTop",
      "org.Exceptions.NotFoundException",
      "org.Exceptions.NoUsersInDatabaseException",
      "org.Model.Playlist.PlaylistRandom",
      "org.Exceptions.NoArtistsInDatabaseException",
      "org.Exceptions.NoMusicsInDatabaseException",
      "org.Exceptions.NoReproductionsInDatabaseException",
      "org.Model.Playlist.PlaylistCreator",
      "org.Exceptions.AlreadyExistsException",
      "org.Model.Music.MusicReproduction",
      "org.Model.Playlist.PlaylistFavorites"
    );
  }
}
