/*
 * This file was automatically generated by EvoSuite
 * Mon May 04 17:37:13 GMT 2026
 */

package org.Controller;

import org.junit.Test;
import org.junit.Ignore;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.LocalDate;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import org.Controller.dtos.MusicInfo;
import org.Model.Album.Album;
import org.Model.Music.Music;
import org.Model.Playlist.Playlist;
import org.Model.SpotifUM;
import org.Model.User.User;
import org.evosuite.runtime.mock.java.time.MockLocalDate;
public class Controller_ESTest {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.createAlbum((String) null, "j1)km}Y06v`h");
      assertEquals("\u2705 \u00C1lbum \"null\" criado com sucesso!", string0);
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      Controller controller0 = new Controller();
      controller0.createAlbum("", "");
      String string0 = controller0.addMusic("", "\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", "N\u00E3o existe utilizadores com playlists.", "\u2705 \u00C1lbum \"\" criado com sucesso!", "@Ia", "N\u00E3o existe utilizadores com playlists.", "", 545, true, "\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.");
      assertEquals("\u2705 M\u00FAsica \"\" adicionada com sucesso!", string0);
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Controller controller0 = new Controller(spotifUM0);
      boolean boolean0 = controller0.loginWithMessage("\u274C Erro ao obter o nome da playlist: null", "\u274C Erro ao obter o artista mais reproduzido: N\u00E3o existem artistas na base de dados.");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser("-2", "-2", "-2", "-2");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      boolean boolean0 = controller0.loginWithMessage("-2", "-2");
      assertTrue(boolean0);
      
      String string1 = controller0.setPremiumBasePlan();
      assertEquals("\u2728 Plano PremiumBase ativado. Boa escolha!", string1);
      
      controller0.addToCurrentUserPlaylists("-2");
      String string2 = controller0.setPlaylistAsPublic(0);
      assertEquals("\u2705 Playlist \"-2\" definida como p\u00FAblica.", string2);
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      Controller controller0 = new Controller();
      controller0.addNewUser("@", "@", "@", "@");
      controller0.loginWithMessage("@", "@");
      MusicInfo musicInfo0 = controller0.playMusic("kM^");
      assertEquals("", musicInfo0.getUrl());
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.listUserPlaylists();
      assertEquals("\u274C Erro ao listar playlists: null", string0);
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      String string0 = controller0.listPublicPlaylists();
      assertEquals("\u274C Erro ao listar playlists: null", string0);
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.listPlaylistMusics(207);
      assertEquals("\u274C Erro ao listar m\u00FAsicas da playlist: null", string0);
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      String string0 = controller0.listAllMusics();
      assertEquals("\u274C Erro ao listar m\u00FAsicas: null", string0);
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      String string0 = controller0.listAllGenres();
      assertEquals("\u274C Erro ao listar g\u00E9neros: null", string0);
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      String string0 = controller0.listAllAlbums();
      assertEquals("\u274C Erro ao listar \u00E1lbuns: null", string0);
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.getUserWithMostReproductions();
      assertEquals("\u274C Erro ao obter o utilizador que ouviu mais m\u00FAsicas: N\u00E3o existem utilizadores na base de dados.", string0);
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser("", "", "=n$}{<=D$,UB", "$v");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      String string1 = controller0.getUserWithMostPoints();
      assertEquals("\uD83C\uDFC6 Utilizador com mais pontos:  com 0 pontos.", string1);
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.getUserWithMostPlaylists();
      assertEquals("\u274C Erro ao obter o utilizador com mais playlists: N\u00E3o existem utilizadores na base de dados.", string0);
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      Optional<List<String>> optional0 = controller0.getRandomPlaylistMusicNames();
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      String string0 = controller0.getPublicPlaylistCount();
      assertEquals("\u274C Erro ao obter o n\u00FAmero de playlists p\u00FAblicas: null", string0);
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      Controller controller0 = new Controller();
      Optional<List<String>> optional0 = controller0.getPlaylistMusicNames((-41));
      assertNotNull(optional0);
  }
@Ignore("EvoSuite: depends on playlist state")
@Test(timeout = 4000)
public void test017()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser("}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      boolean boolean0 = controller0.loginWithMessage("}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ");
      assertTrue(boolean0);
      
      String string1 = controller0.setPremiumBasePlan();
      controller0.addToCurrentUserPlaylists("\u2728 Plano PremiumBase ativado. Boa escolha!");
      String string2 = controller0.getPlaylistId(0);
      assertTrue(string2.equals((Object)string1));
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      Controller controller0 = new Controller();
      controller0.addMusic("pW1jhA[I", "pW1jhA[I", "pW1jhA[I", "pW1jhA[I", "pW1jhA[I", "~_+0\"?;ko{", "*S", 96, true, "~_+0\"?;ko{");
      String string0 = controller0.getMostReproducedMusic();
      assertEquals("\uD83C\uDFB5 M\u00FAsica mais reproduzida: pW1jhA[I - pW1jhA[I", string0);
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      HashMap<String, Music> hashMap0 = new HashMap<String, Music>();
      SpotifUM spotifUM0 = new SpotifUM();
      Map<Integer, Playlist> map0 = spotifUM0.getPublicPlaylists();
      Map<String, User> map1 = spotifUM0.getUsers();
      Map<String, Album> map2 = spotifUM0.getAlbums();
      HashMap<String, Integer> hashMap1 = new HashMap<String, Integer>();
    Integer integer0 = Integer.valueOf(-3);
      hashMap1.put("", integer0);
      SpotifUM spotifUM1 = new SpotifUM(hashMap0, map0, map1, map2, hashMap1, hashMap1);
      Controller controller0 = new Controller(spotifUM1);
      String string0 = controller0.getMostReproducedGenre();
      assertEquals("\uD83C\uDFB6 G\u00E9nero mais reproduzido: ", string0);
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.incrementArtistReproductions("s(");
      Controller controller0 = new Controller(spotifUM0);
      String string0 = controller0.getMostReproducedArtist();
      assertEquals("\uD83C\uDFA4 Artista mais reproduzido: s( - 1\n", string0);
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      Controller controller0 = new Controller();
      Optional<List<String>> optional0 = controller0.getFavoritePlaylistMusicNames(false, 174);
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      Controller controller0 = new Controller();
      Optional<List<String>> optional0 = controller0.getAlbumMusicNames(")EpTa~@t");
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Controller controller0 = new Controller(spotifUM0);
      String string0 = controller0.exportModel((String) null);
      assertEquals("\u274C Erro ao exportar a base de dados: null", string0);
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser("xci,[\"z`5|yn#/j~", "xci,[\"z`5|yn#/j~", "xci,[\"z`5|yn#/j~", "xci,[\"z`5|yn#/j~");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      boolean boolean0 = controller0.loginWithMessage("xci,[\"z`5|yn#/j~", "xci,[\"z`5|yn#/j~");
      assertTrue(boolean0);
      
      controller0.addMusic("Electronic Vibes", "", "n&XYh0Imm2Z", "", "", "#WsG'[", "o1Acm|", (-96), true, "xci,[\"z`5|yn#/j~");
      String string1 = controller0.createGenrePlaylist("cDLEr0d(T_iA8nw", "#WsG'[", 1990);
      assertEquals("\u2705 Playlist \"cDLEr0d(T_iA8nw\" criada com sucesso!", string1);
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser("@", "@", "@", "@");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      boolean boolean0 = controller0.loginWithMessage("@", "@");
      assertTrue(boolean0);
      
      String string1 = controller0.changeCurrentUserUserName("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.");
      assertEquals("\u2705 Nome de utilizador alterado com sucesso!", string1);
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser("", "", "", "");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      boolean boolean0 = controller0.loginWithMessage("", "");
      assertTrue(boolean0);
      
      String string1 = controller0.setFreePlan();
      assertEquals("\u2705 Plano Free selecionado. Desfrute da m\u00FAsica com an\u00FAncios!", string1);
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      Controller controller0 = new Controller();
      controller0.addMusic("", "", "Ku$hw|/iM;G,;", "", "Ku$hw|/iM;G,;", "Ku$hw|/iM;G,;", "]bzd,hE!QfVm.vbH3", (-2565), true, "");
      boolean boolean0 = controller0.musicExists("");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      Controller controller0 = new Controller();
      controller0.addNewUser("@", "@", "@", "@");
      controller0.loginWithMessage("@", "@");
      boolean boolean0 = controller0.isPasswordCorrect("@");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser("}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      boolean boolean0 = controller0.loginWithMessage("}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ");
      assertTrue(boolean0);
      
      boolean boolean1 = controller0.isPasswordCorrect("\uD83C\uDFB5 Lista de m\u00FAsicas na playlist:\n\nN\u00E3o encontrado: -53");
      assertFalse(boolean1 == boolean0);
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      Controller controller0 = new Controller();
      LocalDate localDate0 = MockLocalDate.now();
      String string0 = controller0.getUserWithMostReproductions((LocalDate) null, localDate0);
      assertEquals("\u274C Erro ao obter o utilizador que ouviu mais m\u00FAsicas: N\u00E3o existem utilizadores na base de dados.", string0);
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      SpotifUM spotifUM0 = controller0.getSpotifUM();
      assertNull(spotifUM0);
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Controller controller0 = new Controller(spotifUM0);
      spotifUM0.populateDatabase();
      SpotifUM spotifUM1 = controller0.getSpotifUM();
      assertSame(spotifUM1, spotifUM0);
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser("@", "@", "@", "@");
      controller0.loginWithMessage("@", "@");
      String string1 = controller0.getCurrentUserPlan();
      assertFalse(string1.equals((Object)string0));
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser("}>s,dNGp57]5=Q", "}>s,dNGp57]5=Q", "}>s,dNGp57]5=Q", "}>s,dNGp57]5=Q");
      controller0.loginWithMessage("}>s,dNGp57]5=Q", "}>s,dNGp57]5=Q");
      String string1 = controller0.getCurrentUser();
      assertFalse(string1.equals((Object)string0));
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      Controller controller0 = new Controller();
      controller0.addNewUser("Td", "Td", "Td", "Td");
      controller0.loginWithMessage("Td", "Td");
      controller0.setPremiumTopPlan();
      boolean boolean0 = controller0.currentUserAccessToFavorites();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      Controller controller0 = new Controller();
      controller0.addNewUser("}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ");
      controller0.loginWithMessage("}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ");
      boolean boolean0 = controller0.currentUserAccessToFavorites();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser("", "", "", "");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      boolean boolean0 = controller0.loginWithMessage("", "");
      assertTrue(boolean0);
      
      String string1 = controller0.changeCurrentUserPassword("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.");
      assertEquals("\u2705 Password alterada com sucesso!", string1);
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser("", "", "", "");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      boolean boolean0 = controller0.loginWithMessage("", "");
      assertTrue(boolean0);
      
      String string1 = controller0.changeCurrentUserEmail("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.");
      assertEquals("\u2705 Email alterado com sucesso!", string1);
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      Controller controller0 = new Controller();
      controller0.addNewUser("}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ");
      controller0.loginWithMessage("}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ");
      controller0.setPremiumBasePlan();
      boolean boolean0 = controller0.canCurrentUserSkip();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser("}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      boolean boolean0 = controller0.loginWithMessage("}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ");
      assertTrue(boolean0);
      
      boolean boolean1 = controller0.canCurrentUserSkip();
      assertFalse(boolean1 == boolean0);
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      Controller controller0 = new Controller();
      controller0.addNewUser("}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ");
      controller0.loginWithMessage("}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ");
      controller0.setPremiumBasePlan();
      boolean boolean0 = controller0.canCurrentUserChooseWhatToPlay();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser("", "", "", "");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      boolean boolean0 = controller0.loginWithMessage("", "");
      assertTrue(boolean0);
      
      boolean boolean1 = controller0.canCurrentUserChooseWhatToPlay();
      assertFalse(boolean1 == boolean0);
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      Controller controller0 = new Controller();
      controller0.createAlbum("", "");
      boolean boolean0 = controller0.albumExists("");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      Controller controller0 = new Controller();
      // Undeclared exception!
      try { 
        controller0.setSpotifUM((SpotifUM) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      // Undeclared exception!
      try { 
        controller0.currentUserHasLibrary();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Controller.Controller", e);
      }
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      // Undeclared exception!
      try { 
        controller0.albumExists("\u274C Erro ao definir a playlist como p\u00FAblica: null");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Controller.Controller", e);
      }
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      // Undeclared exception!
      try { 
        controller0.addNewUser("/,7-N.HGDHJXtn ", "/,7-N.HGDHJXtn ", "/,7-N.HGDHJXtn ", "/,7-N.HGDHJXtn ");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Controller.Controller", e);
      }
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      try {
                new Controller((Controller) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Controller.Controller", e);
      }
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      Controller controller0 = new Controller();
      SpotifUM spotifUM0 = new SpotifUM();
      controller0.setSpotifUM(spotifUM0);
      assertEquals("SpotifUM(...)", spotifUM0.toString());
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Controller controller0 = new Controller(spotifUM0);
      SpotifUM spotifUM1 = controller0.getSpotifUM();
      assertSame(spotifUM1, spotifUM0);
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser("-2", "-2", "-2", "-2");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      String string1 = controller0.getUserWithMostReproductions();
      assertEquals("N\u00E3o existe utilizadores com reprodu\u00E7\u00F5es.", string1);
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser("Td", "Td", "Td", "Td");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      String string1 = controller0.getUserWithMostPlaylists();
      assertEquals("N\u00E3o existe utilizadores com playlists.", string1);
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser("}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      boolean boolean0 = controller0.loginWithMessage("}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ");
      assertTrue(boolean0);
      
      String string1 = controller0.setPremiumBasePlan();
      assertEquals("\u2728 Plano PremiumBase ativado. Boa escolha!", string1);
      
      controller0.addToCurrentUserPlaylists("\u2728 Plano PremiumBase ativado. Boa escolha!");
      String string2 = controller0.getUserWithMostPlaylists();
      assertEquals("\uD83D\uDCDA Utilizador com mais playlists: }>s,dNLGp57]5=YQ com 1 playlists.", string2);
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      Controller controller0 = new Controller(spotifUM0);
      Optional<List<String>> optional0 = controller0.getRandomPlaylistMusicNames();
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      Controller controller0 = new Controller();
      controller0.addNewUser("}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ");
      controller0.loginWithMessage("}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ");
      Optional<List<String>> optional0 = controller0.getFavoritePlaylistMusicNames(true, 1);
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      Controller controller0 = new Controller();
      controller0.createAlbum("", "");
      controller0.addMusic("", "", "", "", "", "", "", 1, true, "");
      Optional<List<String>> optional0 = controller0.getAlbumMusicNames("");
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      Controller controller0 = new Controller();
      controller0.addNewUser("", "", "", "");
      controller0.loginWithMessage("", "");
      controller0.setPremiumTopPlan();
      controller0.addToCurrentUserPlaylists("");
      Optional<List<String>> optional0 = controller0.getPlaylistMusicNames(0);
      assertNotNull(optional0);
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.listAllGenres();
      assertEquals("\uD83D\uDCED N\u00E3o existem g\u00E9neros dispon\u00EDveis.", string0);
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      Controller controller0 = new Controller(spotifUM0);
      String string0 = controller0.listAllGenres();
      assertEquals("\uD83C\uDFB6 Lista de g\u00E9neros dispon\u00EDveis:\n\n\u2022 Electronic\n\u2022 Hino\n\u2022 Hip-Hop\n\u2022 Pop\n\u2022 Rock\n", string0);
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.listAllAlbums();
      assertEquals("\uD83D\uDCED N\u00E3o existem \u00E1lbuns dispon\u00EDveis.", string0);
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      Controller controller0 = new Controller();
      controller0.createAlbum("", "");
      String string0 = controller0.listAllAlbums();
      assertEquals("\uD83D\uDDBC\uFE0F  Lista de \u00E1lbuns dispon\u00EDveis:\n\n\uD83D\uDCC0  \u2014 \n", string0);
  }
@Ignore("EvoSuite: depends on playlist state")
@Test(timeout = 4000)
public void test062()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser("", "", "", "");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      boolean boolean0 = controller0.loginWithMessage("", "");
      assertTrue(boolean0);
      
      String string1 = controller0.setPremiumBasePlan();
      assertEquals("\u2728 Plano PremiumBase ativado. Boa escolha!", string1);
      
      controller0.addToCurrentUserPlaylists("");
      String string2 = controller0.listPlaylistMusics(0);
      assertEquals("", string2);
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser("}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      boolean boolean0 = controller0.loginWithMessage("}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ");
      assertTrue(boolean0);
      
      String string1 = controller0.setPremiumBasePlan();
      assertEquals("\u2728 Plano PremiumBase ativado. Boa escolha!", string1);
      
      String string2 = controller0.listPlaylistMusics((-89));
      assertEquals("\uD83C\uDFB5 Lista de m\u00FAsicas na playlist:\n\nN\u00E3o encontrado: -89", string2);
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.listAllMusics();
      assertEquals("\uD83D\uDCED N\u00E3o existem m\u00FAsicas dispon\u00EDveis.", string0);
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.listPublicPlaylists();
      assertEquals("\uD83D\uDCED N\u00E3o existem playlists p\u00FAblicas.", string0);
  }
@Ignore("EvoSuite: depends on playlist order")
@Test(timeout = 4000)
public void test066()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      spotifUM0.populateDatabase();
      Controller controller0 = new Controller(spotifUM0);
      String string0 = controller0.listPublicPlaylists();
      assertEquals("\uD83D\uDCDA Playlists P\u00FAblicas:\n\uD83C\uDFB5 [#000] Top Global                | Autor: Spotify        \n\uD83C\uDFB5 [#001] Rock Legends              | Autor: RockFM         \n\uD83C\uDFB5 [#002] Hip-Hop Nation            | Autor: HipHopTV       \n\uD83C\uDFB5 [#003] Electronic Vibes          | Autor: EDM.com        \n\uD83C\uDFB5 [#004] Throwback Hits            | Autor: OldiesFM       \n\uD83C\uDFB5 [#005] Portuguese Pride          | Autor: RTP            \n", string0);
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser("Td", "Td", "Td", "Td");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      boolean boolean0 = controller0.loginWithMessage("Td", "Td");
      assertTrue(boolean0);
      
      String string1 = controller0.setPremiumTopPlan();
      assertEquals("\uD83D\uDC51 Bem-vindo ao topo! Plano PremiumTop ativado com sucesso.", string1);
      
      String string2 = controller0.listUserPlaylists();
      assertEquals("\uD83D\uDCED N\u00E3o existem playlists.", string2);
  }
@Ignore("EvoSuite: depends on playlist order")
@Test(timeout = 4000)
public void test068()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser("}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      boolean boolean0 = controller0.loginWithMessage("}>s,dNLGp57]5=YQ", "}>s,dNLGp57]5=YQ");
      assertTrue(boolean0);
      
      String string1 = controller0.setPremiumBasePlan();
      assertEquals("\u2728 Plano PremiumBase ativado. Boa escolha!", string1);
      
      controller0.addToCurrentUserPlaylists("i_OQM3aE)H:v");
      String string2 = controller0.listUserPlaylists();
      assertEquals("\uD83D\uDCDA As tuas playlists:\n\uD83C\uDFB5 [#000] i_OQM3aE)H:v              | Autor: }>s,dNLGp57]5=YQ\n", string2);
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser("-2", "-2", "-2", "-2");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      boolean boolean0 = controller0.loginWithMessage("-2", "-2");
      assertTrue(boolean0);
      
      String string1 = controller0.setPremiumTopPlan();
      assertEquals("\uD83D\uDC51 Bem-vindo ao topo! Plano PremiumTop ativado com sucesso.", string1);
      
      boolean boolean1 = controller0.currentUserHasLibrary();
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      Controller controller0 = new Controller();
      boolean boolean0 = controller0.currentUserHasLibrary();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser("|H|aFzWu%y", "", "|H|aFzWu%y", "|H|aFzWu%y");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      String string1 = controller0.addNewUser("|H|aFzWu%y", "|H|aFzWu%y", "|H|aFzWu%y", "|H|aFzWu%y");
      assertEquals("\u26A0\uFE0F J\u00E1 existe um utilizador com esse nome. Tenta outro!", string1);
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addNewUser("-2", "-2", "-2", "-2");
      assertEquals("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
      
      boolean boolean0 = controller0.loginWithMessage("-2", "-2");
      assertTrue(boolean0);
      
      boolean boolean1 = controller0.currentUserHasLibrary();
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      Controller controller0 = new Controller();
      // Undeclared exception!
      try { 
        controller0.canCurrentUserSkip();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.getPublicPlaylistCount();
      assertEquals("\uD83D\uDCCA N\u00FAmero de playlists p\u00FAblicas: 0", string0);
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addMusicToCurrentUserPlaylist((-302), "\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.");
      assertEquals("\u274C Erro ao adicionar a m\u00FAsica \u00E0 playlist: N\u00E3o encontrado: \u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.", string0);
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      Controller controller0 = new Controller();
      // Undeclared exception!
      try { 
        controller0.getCurrentUserPlan();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      Controller controller0 = new Controller();
      boolean boolean0 = controller0.musicExists("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.setPlaylistAsPublic(0);
      assertEquals("\u274C Erro ao definir a playlist como p\u00FAblica: null", string0);
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      Controller controller0 = new Controller();
      // Undeclared exception!
      try { 
        controller0.setPremiumTopPlan();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Controller.Controller", e);
      }
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.changeCurrentUserUserName("fDm!v%^#oHAH?Ko");
      assertEquals("\u274C Erro ao alterar o nome de utilizador: null", string0);
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      Controller controller0 = new Controller();
      boolean boolean0 = controller0.albumExists("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.getUserWithMostPoints();
      assertEquals("\u274C Erro ao obter o utilizador com mais pontos: N\u00E3o existem utilizadores na base de dados.", string0);
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      Controller controller0 = new Controller();
      // Undeclared exception!
      try { 
        controller0.currentUserAccessToFavorites();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.createGenrePlaylist("cDLEr0d(T_iA8nw", "#WsG'[", 1990);
      assertEquals("\u274C Erro ao criar a playlist: null", string0);
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      Controller controller0 = new Controller();
      // Undeclared exception!
      try { 
        controller0.getCurrentUser();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Controller.Controller", e);
      }
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      Controller controller0 = new Controller();
      // Undeclared exception!
      try { 
        controller0.changeCurrentUserPassword("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addPublicPlaylistToLibrary((-57));
      assertEquals("\u274C Erro ao adicionar a playlist \u00E0 biblioteca: N\u00E3o encontrado: -57", string0);
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.getMostReproducedMusic();
      assertEquals("\u274C Erro ao obter a m\u00FAsica mais reproduzida: N\u00E3o existem m\u00FAsicas na base de dados.", string0);
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      Controller controller0 = new Controller();
      // Undeclared exception!
      try { 
        controller0.isPasswordCorrect("-2");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.removeMusicFromPlaylist("N:teTqao`", (-3126));
      assertEquals("\u274C Erro ao remover a m\u00FAsica da playlist: N\u00E3o encontrado: N:teTqao`", string0);
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      Controller controller0 = new Controller();
      controller0.addMusic("Electronic Vibes", "", "n&XYh0Imm2Z", "", "", "#WsG'[", "o1Acm|", (-96), true, "xci,[\"z`5|yn#/j~");
      String string0 = controller0.listAllMusics();
      assertEquals("\uD83C\uDFB5 Lista de m\u00FAsicas dispon\u00EDveis:\n\n\uD83C\uDFB6 Electronic Vibes \u2014 \n", string0);
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.getPlaylistId(0);
      assertEquals("\u274C Erro ao obter o nome da playlist: null", string0);
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      Controller controller0 = new Controller();
      // Undeclared exception!
      try { 
        controller0.changeCurrentUserEmail("\u2705 Utilizador registado com sucesso! J\u00E1 podes iniciar sess\u00E3o.");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      Controller controller0 = new Controller();
      // Undeclared exception!
      try { 
        controller0.setPremiumBasePlan();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Controller.Controller", e);
      }
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      Controller controller0 = new Controller((SpotifUM) null);
      String string0 = controller0.createAlbum("\u2705 Base de dados importada com sucesso!", "Dh2gL&9 ,");
      assertEquals("\u274C Erro ao criar o \u00E1lbum: null", string0);
  }
@Ignore("EvoSuite: filesystem path dependent")
@Test(timeout = 4000)
public void test096()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.exportModel("Tu/W");
      assertEquals("\u2705 Base de dados exportada com sucesso!", string0);
      
      String string1 = controller0.importModel("Tu/W");
      assertEquals("\u2705 Base de dados importada com sucesso!", string1);
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.getMostReproducedArtist();
      assertEquals("\u274C Erro ao obter o artista mais reproduzido: N\u00E3o existem artistas na base de dados.", string0);
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      Controller controller0 = new Controller();
      Controller controller1 = new Controller(controller0);
      assertFalse(controller1.equals((Object)controller0));
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      SpotifUM spotifUM0 = new SpotifUM();
      Controller controller0 = new Controller(spotifUM0);
      String string0 = controller0.getMostReproducedGenre();
      assertEquals("\u274C Erro ao obter o g\u00E9nero mais reproduzido: N\u00E3o existem reprodu\u00E7\u00F5es na base de dados.", string0);
  }
@Ignore("EvoSuite: filesystem path dependent")
@Test(timeout = 4000)
public void test100()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.importModel("n<p=G-+");
      assertEquals("\u274C Erro ao importar a base de dados: Erro ao importar o objeto: null", string0);
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      Controller controller0 = new Controller();
      // Undeclared exception!
      try { 
        controller0.canCurrentUserChooseWhatToPlay();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.SpotifUM", e);
      }
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      Controller controller0 = new Controller();
      String string0 = controller0.addToCurrentUserPlaylists("i_OQM3aE)H:v");
      assertEquals("\u274C Erro ao adicionar a playlist: null", string0);
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      Controller controller0 = new Controller();
      // Undeclared exception!
      try { 
        controller0.setFreePlan();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Controller.Controller", e);
      }
  }
}
