/*
 * This file was automatically generated by EvoSuite
 * Sat May 02 21:42:38 GMT 2026
 */

package org.Model.Music;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
public class Music_ESTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Music music0 = new Music("2c%:PV'7<g", "`=$9W?5'$m/6coa", "fyskh?$", (String) null, "`=$9W?5'$m/6coa", "IE|li{Dh", (String) null, (-4616), true);
      music0.play();
      assertEquals(1, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Music music0 = new Music("Yc_x#(5k?$6GOMtb7Q{", "1vntSE.~c", "Yc_x#(5k?$6GOMtb7Q{", "Yc_x#(5k?$6GOMtb7Q{", "", "$#wK9i~KSgg ^o", "Nao", 1802, false);
      music0.play();
      assertEquals(1, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Music music0 = new Music("", "", "", (String) null, "k{EMCEkx{,T26y*", "", (String) null, 1, true);
      boolean boolean0 = music0.isExplicit();
      assertEquals(1, music0.getDuration());
      assertEquals("", music0.getGenre());
      assertEquals("", music0.getName());
      assertTrue(boolean0);
      assertEquals("", music0.getPublisher());
      assertEquals(0, music0.getReproductions());
      assertEquals("k{EMCEkx{,T26y*", music0.getMusicalFigures());
      assertEquals("", music0.getInterpreter());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Music music0 = new Music("", "", "Nao", "", "", "", (String) null, 0, true);
      music0.setReproductions((-553));
      int int0 = music0.getReproductions();
      assertEquals((-553), int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Music music0 = new Music("yv_s=d", "", (String) null, "yv_s=d", "Nome: ", "S*}OoJ=hUDj\"$^", "Linhas Musicais: ", 1, false);
      String string0 = music0.getPublisher();
      assertFalse(music0.isExplicit());
      assertEquals("S*}OoJ=hUDj\"$^", music0.getGenre());
      assertEquals(1, music0.getDuration());
      assertNull(string0);
      assertEquals(0, music0.getReproductions());
      assertEquals("", music0.getInterpreter());
      assertEquals("Linhas Musicais: ", music0.getAlbum());
      assertEquals("Nome: ", music0.getMusicalFigures());
      assertEquals("yv_s=d", music0.getLyrics());
      assertEquals("yv_s=d", music0.getName());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Music music0 = new Music();
      music0.setPublisher("Nao");
      music0.getPublisher();
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getReproductions());
      assertEquals(0, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Music music0 = new Music();
      music0.setName((String) null);
      music0.getName();
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getReproductions());
      assertEquals(0, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Music music0 = new Music("", "(p,S:XqZ", "", "", "(RV7W3_(b!8", "mL!", "", (-1), true);
      assertEquals("", music0.getName());
      
      music0.setName("(RV7W3_(b!8");
      music0.getName();
      assertEquals("", music0.getLyrics());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Music music0 = new Music();
      music0.setMusicalFigures((String) null);
      music0.getMusicalFigures();
      assertEquals(0, music0.getReproductions());
      assertEquals(0, music0.getDuration());
      assertFalse(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Music music0 = new Music("", "", "Nao", "", "", "", (String) null, 0, true);
      assertEquals("", music0.getMusicalFigures());
      
      music0.setMusicalFigures("#V");
      music0.getMusicalFigures();
      assertEquals("Nao", music0.getPublisher());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Music music0 = new Music("2c%:PV'7<g", "`=$9W?5'$m/6coa", "fyskh?$", (String) null, "`=$9W?5'$m/6coa", "IE|li{Dh", (String) null, (-4616), true);
      String string0 = music0.getLyrics();
      assertEquals("2c%:PV'7<g", music0.getName());
      assertEquals("`=$9W?5'$m/6coa", music0.getInterpreter());
      assertTrue(music0.isExplicit());
      assertEquals(0, music0.getReproductions());
      assertEquals("IE|li{Dh", music0.getGenre());
      assertEquals((-4616), music0.getDuration());
      assertNull(string0);
      assertEquals("fyskh?$", music0.getPublisher());
      assertEquals("`=$9W?5'$m/6coa", music0.getMusicalFigures());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Music music0 = new Music("H_wq9y9", "H_wq9y9", "", "'Rl&1Z*[|y!U;(}", "'Rl&1Z*[|y!U;(}", "H_wq9y9", "Un]q&,A5b0Ve]", 1238, true);
      String string0 = music0.getLyrics();
      assertEquals(0, music0.getReproductions());
      assertEquals("", music0.getPublisher());
      assertEquals("H_wq9y9", music0.getName());
      assertEquals("Un]q&,A5b0Ve]", music0.getAlbum());
      assertEquals(1238, music0.getDuration());
      assertEquals("H_wq9y9", music0.getInterpreter());
      assertEquals("'Rl&1Z*[|y!U;(}", music0.getMusicalFigures());
      assertEquals("H_wq9y9", music0.getGenre());
      assertTrue(music0.isExplicit());
      assertEquals("'Rl&1Z*[|y!U;(}", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Music music0 = new Music();
      music0.setInterpreter((String) null);
      music0.getInterpreter();
      assertEquals(0, music0.getDuration());
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Music music0 = new Music("", "", "", "", "", "", "", 0, false);
      music0.setInterpreter("Linhas Musicais: ");
      music0.getInterpreter();
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Music music0 = new Music();
      music0.setGenre((String) null);
      music0.getGenre();
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getDuration());
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Music music0 = new Music("", "(p,S:XqZ", "", "", "(RV7W3_(b!8", "mL!", "", (-1), true);
      String string0 = music0.getGenre();
      assertEquals("", music0.getName());
      assertTrue(music0.isExplicit());
      assertEquals("(p,S:XqZ", music0.getInterpreter());
      assertEquals("mL!", string0);
      assertEquals("", music0.getLyrics());
      assertEquals("", music0.getAlbum());
      assertEquals(0, music0.getReproductions());
      assertEquals("(RV7W3_(b!8", music0.getMusicalFigures());
      assertEquals((-1), music0.getDuration());
      assertEquals("", music0.getPublisher());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Music music0 = new Music("", "", "Nao", "", "", "", (String) null, 0, true);
      music0.setDuration(261);
      int int0 = music0.getDuration();
      assertEquals(261, int0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Music music0 = new Music();
      music0.setDuration((-1));
      int int0 = music0.getDuration();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Music music0 = new Music("H_wq9y9", "H_wq9y9", "", "'Rl&1Z*[|y!U;(}", "'Rl&1Z*[|y!U;(}", "H_wq9y9", "Un]q&,A5b0Ve]", 1238, true);
      String string0 = music0.getAlbum();
      assertEquals(1238, music0.getDuration());
      assertEquals("H_wq9y9", music0.getInterpreter());
      assertTrue(music0.isExplicit());
      assertEquals("'Rl&1Z*[|y!U;(}", music0.getLyrics());
      assertEquals("", music0.getPublisher());
      assertEquals("H_wq9y9", music0.getName());
      assertEquals("Un]q&,A5b0Ve]", string0);
      assertEquals("'Rl&1Z*[|y!U;(}", music0.getMusicalFigures());
      assertEquals("H_wq9y9", music0.getGenre());
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Music music0 = new Music();
      music0.setReproductions(824);
      music0.clone();
      assertEquals(824, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Music music0 = new Music("", "(p,S:XqZ", "", "", "(RV7W3_(b!8", "mL!", "", (-1), true);
      music0.setReproductions((-2886));
      music0.clone();
      assertEquals((-2886), music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Music music0 = new Music("", "", "", "", "", "", "", 2758, true);
      Music music1 = music0.clone();
      assertEquals(2758, music0.getDuration());
      assertTrue(music1.isExplicit());
      assertTrue(music1.equals((Object)music0));
      assertEquals(0, music1.getReproductions());
      assertEquals(2758, music1.getDuration());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      try {
                new Music((Music) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.Model.Music.Music", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Music music0 = new Music("", "", "", "", "", "", "", 0, false);
      music0.getMusicalFigures();
      assertEquals(0, music0.getDuration());
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Music music0 = new Music();
      music0.getGenre();
      assertEquals(0, music0.getDuration());
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Music music0 = new Music();
      int int0 = music0.getReproductions();
      assertFalse(music0.isExplicit());
      assertEquals(0, int0);
      assertEquals(0, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Music music0 = new Music();
      music0.getAlbum();
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getDuration());
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Music music0 = new Music("", "", "", "", "", "", "", 0, false);
      music0.getName();
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Music music0 = new Music();
      music0.getLyrics();
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Music music0 = new Music();
      boolean boolean0 = music0.isExplicit();
      assertFalse(boolean0);
      assertEquals(0, music0.getReproductions());
      assertEquals(0, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Music music0 = new Music();
      music0.getInterpreter();
      assertEquals(0, music0.getDuration());
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Music music0 = new Music();
      music0.getPublisher();
      assertEquals(0, music0.getDuration());
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Music music0 = new Music();
      int int0 = music0.getDuration();
      assertFalse(music0.isExplicit());
      assertEquals(0, int0);
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Music music0 = new Music();
      music0.setName((String) null);
      Music music1 = new Music(music0);
      boolean boolean0 = music0.equals(music1);
      assertEquals(0, music1.getDuration());
      assertFalse(music1.isExplicit());
      assertTrue(boolean0);
      assertEquals(0, music1.getReproductions());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Music music0 = new Music();
      Music music1 = new Music(music0);
      boolean boolean0 = music1.equals(music0);
      assertTrue(boolean0);
      assertEquals(0, music1.getDuration());
      assertFalse(music1.isExplicit());
      assertEquals(0, music1.getReproductions());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Music music0 = new Music();
      boolean boolean0 = music0.equals(music0);
      assertEquals(0, music0.getReproductions());
      assertEquals(0, music0.getDuration());
      assertTrue(boolean0);
      assertFalse(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Music music0 = new Music();
      boolean boolean0 = music0.equals((Object) null);
      assertEquals(0, music0.getDuration());
      assertFalse(music0.isExplicit());
      assertFalse(boolean0);
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Music music0 = new Music((String) null, (String) null, (String) null, (String) null, (String) null, "Genero Musical: ", "Genero Musical: ", (-7803), true);
      String string0 = music0.toString();
      assertEquals("Nome: null\nInterprete: null\nEditora: null\nLetra: null\nLinhas Musicais: null\nGenero Musical: Genero Musical: \nAlbum: Genero Musical: \nDuracao: -7803\nReproducoes: 0\nExplicita: Sim\n", string0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Music music0 = new Music();
      String string0 = music0.toString();
      assertEquals("Nome: \nInterprete: \nEditora: \nLetra: \nLinhas Musicais: \nGenero Musical: \nAlbum: \nDuracao: 0\nReproducoes: 0\nExplicita: Nao\n", string0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Music music0 = new Music();
      music0.setLyrics("F+<cc(,kAv%zAQ7");
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getDuration());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Music music0 = new Music();
      music0.setExplicit(false);
      assertEquals(0, music0.getDuration());
      assertEquals(0, music0.getReproductions());
      assertFalse(music0.isExplicit());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Music music0 = new Music();
      music0.play();
      int int0 = music0.getReproductions();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Music music0 = new Music();
      music0.setAlbum((String) null);
      music0.getAlbum();
      assertFalse(music0.isExplicit());
      assertEquals(0, music0.getDuration());
      assertEquals(0, music0.getReproductions());
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Music music0 = new Music();
      music0.setName((String) null);
      
      //  // Unstable assertion: assertEquals(0, music1.getDuration());
      //  // Unstable assertion: assertEquals(0, music1.getReproductions());
      //  // Unstable assertion: assertFalse(boolean0);
      //  // Unstable assertion: assertTrue(music1.equals((Object)music0));
      //  // Unstable assertion: assertFalse(music1.isExplicit());
  }
}
